### ISSUE TITLE
Java 8 Stream support broken [DATAJPA-742]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1113]
**[Romain Moreau](https://jira.spring.io/secure/ViewProfile.jspa?name=romainmoreau)** opened **[DATAJPA-742](https://jira.spring.io/browse/DATAJPA-742?redirect=false)** and commented

When I call a method of a Repository returning a Java 8 Stream, I get the following exception :

```
org.springframework.beans.NotReadablePropertyException: Invalid property 'query' of bean class [com.sun.proxy.$Proxy51]: Bean property 'query' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:617)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:608)
	at org.springframework.data.jpa.provider.PersistenceProvider$HibernateScrollableResultsIterator.extractHibernateQueryFromQueryImpl(PersistenceProvider.java:442)
	at org.springframework.data.jpa.provider.PersistenceProvider$HibernateScrollableResultsIterator.extractHibernate4Query(PersistenceProvider.java:425)
	at org.springframework.data.jpa.provider.PersistenceProvider$HibernateScrollableResultsIterator.<init>(PersistenceProvider.java:381)
	at org.springframework.data.jpa.provider.PersistenceProvider$1.executeQueryWithResultStream(PersistenceProvider.java:119)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$StreamExecution.doExecute(JpaQueryExecution.java:322)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:77)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:100)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:91)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:431)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:409)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy47.streamAll(Unknown Source)
	at fr.romainmoreau.test.Main.main(Main.java:26)
```

---

**Affects:** 1.9 M1 (Gosling), 1.8.2 (Fowler SR2)

**Reference URL:** https://github.com/romainmoreau/spring-data-jpa-test

**Backported to:** [1.9.1 (Gosling SR1)](https://github.com/spring-projects/spring-data-jpa/milestone/60?closed=1), [1.8.3 (Fowler SR3)](https://github.com/spring-projects/spring-data-jpa/milestone/67?closed=1)

3 votes, 5 watchers

**Comment by Liveitabhi14** [comment]
This might help if someone still faces this issue..
https://medium.com/predictly-on-tech/spring-data-jpa-batching-using-streams-af456ea611fc#:~:text=Line%20%231%20%E2%80%94%20Any%20stream%20operation%20must%20be%20wrapped%20in%20a%20transaction%0ASpring%20will%20throw%20an%20exception%20otherwise
