### ISSUE TITLE
JpaQueryCreator runs into NullPointerException [DATAJPA-1130]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1475]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAJPA-1130](https://jira.spring.io/browse/DATAJPA-1130?redirect=false)** and commented

**XxxId.java**

```java
 
package com.example.model;
 
import java.io.Serializable;
import java.util.Objects;
 
public class XxxId implements Serializable {
	private static final long serialVersionUID = -5183049208770059085L;
 
	private int a;
	
	private String b;
 
	public final int getA() {
		return a;
	}
 
	public final void setA(int a) {
		this.a = a;
	}
 
	public final String getB() {
		return b;
	}
 
	public final void setB(String b) {
		this.b = b;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof XxxId) {
			final XxxId xxxId = (XxxId) obj;
			return xxxId.a == a && xxxId.b.equals(b);
		} else {
			return false;
		}
	}
	
	@Override
	public int hashCode() {
		return Objects.hash(a, b);
	}
}
```

**Xxx.java**

```java
 
package com.example.model;
 
import java.io.Serializable;
import java.util.Objects;
 
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.validation.constraints.Min;
 
@Entity
@IdClass(XxxId.class)
public class Xxx implements Serializable {
	private static final long serialVersionUID = -1273449129220235158L;
 
	@Id
	@Min(2)
	private int a;
	
	@Id
	private String b;
 
	public final int getA() {
		return a;
	}
 
	public final void setA(int a) {
		this.a = a;
	}
 
	public final String getB() {
		return b;
	}
 
	public final void setB(String b) {
		this.b = b;
	}
	
	@Override
	public boolean equals(Object obj) {
		if (obj instanceof Xxx) {
			final Xxx xxx = (Xxx) obj;
			return xxx.a == a && xxx.b.equals(b);
		} else {
			return false;
		}
	}
	
	@Override
	public int hashCode() {
		return Objects.hash(a, b);
	}
}
```

**XxxRepository.java**

```java
 
package com.example.model.repository;
 
import org.springframework.data.jpa.repository.JpaRepository;
 
import com.example.model.Xxx;
import com.example.model.XxxId;
 
public interface XxxRepository extends JpaRepository<Xxx, XxxId> {
 
	boolean existsByA(int a);
}
```

**XxxRepositoryTest.java**

```java
 
package com.example;
 
import javax.transaction.Transactional;
 
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.test.context.junit4.SpringRunner;
 
import com.example.model.repository.XxxRepository;

@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = WebEnvironment.RANDOM_PORT)
@Transactional
public class XxxRepositoryTest {
	
	@Autowired
	private XxxRepository xxxRepository;
 
	@Test
	public void testExistsByA() {
		Assert.assertFalse(xxxRepository.existsByA(1));
	}
}
```

Stack trace:

```
…
Caused by: java.lang.NullPointerException
	at org.hibernate.query.criteria.internal.path.AbstractPathImpl.get(AbstractPathImpl.java:123)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:187)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:143)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:52)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:88)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:73)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:126)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:70)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:103)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:214)
	at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:77)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.<init>(RepositoryFactorySupport.java:436)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:221)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.initAndReturn(RepositoryFactoryBeanSupport.java:277)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:263)
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:101)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
	... 94 more
```

---

**Affects:** 1.11.3 (Ingalls SR3)

**Reference URL:** https://stackoverflow.com/questions/43689542/spring-data-jpa-existsby-projection-for-entity-with-idclass-compound-primary-ke

4 votes, 4 watchers

**Comment by gregturn** [comment]
I jsut wrote this, and it passes just fine.

```java
	@Test
	void shouldExecuteExistsQueryForCompoundIdClassKey() {

		IdClassExampleDepartment dep2 = new IdClassExampleDepartment();
		dep2.setDepartmentId(2L);
		dep2.setName("Dep2");

		IdClassExampleEmployee emp1 = new IdClassExampleEmployee();
		emp1.setEmpId(3L);
		emp1.setDepartment(dep2);
		emp1.setName("White");

		employeeRepositoryWithIdClass.save(emp1);

		assertThat(employeeRepositoryWithIdClass.existsByEmpId(3L)).isTrue();
	}
```

**Comment by schauder** [comment]
So, if no one comes up with a still failing reproducer we can close this, right?

**Comment by gregturn** [comment]
Right.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
