### ISSUE TITLE
Pageable Always Adding From Entity to Sort Field Name [DATAJPA-1332]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1655]
**[Vijay](https://jira.spring.io/secure/ViewProfile.jspa?name=s)** opened **[DATAJPA-1332](https://jira.spring.io/browse/DATAJPA-1332?redirect=false)** and commented

I am having the exact issue that is mentioned on this link https://jira.spring.io/browse/DATAJPA-726
It is mentioned as solved there, but I am getting the same issue, and a search on stackoverflow shows that the problem persists. I am using **SpringBoot 1.5.12.**

Basically, I am doing a pagination on JOIN query as follows

```java
@Query(Select DISTINCT new com.api.dto.FilterDTO(c.id, p.id, CASE WHEN item.dateDue IS NOT NULL THEN item.dateDue ELSE p.dateDue END AS newDateDue) FROM Customer c join c.productOrder p JOIN p.items item ")
List<FilterDTO> findDates(Pageable pageable);
```

And my page request is

```java
Pageable page = new PageRequest(0, 20, Direction.DESC, "newDateDue");
```

However, when i run this I keep getting the error

```java
could not resolve property: newDateDue of: com.api.beans.Customer
```

Evidently, it is searching for the sort field (i.e. newDateDue) in the Customer entity where it is not present.

So my question is
1. Is Pagable not applicable when a JOIN is present ?
2. Then is the only alternative to use native sql query ? But the link provided above says, this has been solved and it works for Spring Data JPA - I would like to continue using Spring Data JPA for this if it works - please help.

Thanks.

Note:There are other queries too on stackoverflow with similiar problems but no solutions. Links are as below
* https://stackoverflow.com/q/43993952/6043669
* https://stackoverflow.com/q/5903774/6043669

---

1 votes, 4 watchers

**Comment by derylspielman** [comment]
I too am facing this exact same issue. It is tacking on the alias "f." of the main entity instead of first searching for alias names in the list of selects. This works if I use "cl.name" as a sort field, but fails if I use alias "clientName".

```
Caused by: org.hibernate.QueryException: could not resolve property: clientName of: com.example.FtmRemoteFileSetting [SELECT NEW com.example.FtmRemoteFileSettingDto(f.fileName, cl.name AS clientName) FROM com.example.FtmRemoteFileSetting f LEFT JOIN f.client cl order by f.clientName asc]
        at org.hibernate.QueryException.generateQueryException(QueryException.java:120)
        at org.hibernate.QueryException.wrapWithQueryString(QueryException.java:103)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.doCompile(QueryTranslatorImpl.java:220)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.compile(QueryTranslatorImpl.java:144)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:113)
        at org.hibernate.engine.query.spi.HQLQueryPlan.<init>(HQLQueryPlan.java:73)
        at org.hibernate.engine.query.spi.QueryPlanCache.getHQLQueryPlan(QueryPlanCache.java:162)
        at org.hibernate.internal.AbstractSharedSessionContract.getQueryPlan(AbstractSharedSessionContract.java:604)
        at org.hibernate.internal.AbstractSharedSessionContract.createQuery(AbstractSharedSessionContract.java:716)
```

**Comment by gregturn** [comment]
Looks like this issue will be resolved via #2863.

**Comment by gregturn** [comment]
If you check https://github.com/spring-projects/spring-data-jpa/commit/39e12eae6d64ba7192835e052a082b93b287d911, you should see that aliasing is now properly handled in sorts, and that the query at the top is included as a test case.

Feel free to check out Spring Data JPA `3.1.0-SNAPSHOT` and test it out for yourself.

**Comment by gregturn** [comment]
Closing this as resolved by the earlier message.

**Comment by matus-krska** [comment]
What about native queries? This is still broken in those
