### ISSUE TITLE
Improve release documentation to include important version upgrades [DATAJPA-1355]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1675]
**[Caleb Cushing](https://jira.spring.io/secure/ViewProfile.jspa?name=xenoterracide)** opened **[DATAJPA-1355](https://jira.spring.io/browse/DATAJPA-1355?redirect=false)** and commented

The issue is, that SB (1.x) (sorry can't keep up with SD train names) code that still compiles blows up when using Stream.

Expectation, 1.x behavior would be preserved instead of new hibernate 5.2 behavior with streams. I understand this may not be feasible, so I'd like to say I also don't see any information on it in the the documentation, and if this can't be fixed, I think the gotcha should be well documented. I'm personally ok with the idea that Streams can't be supported without hibernate 5.2, as we were really just wrapping Collections anyways; which defeats the purpose imho.

In addition to documenting, a better, and perhaps eager (startup) error should added. As it is it's hard to tell where it's even coming from in some cases

p.s. we cant simply upgrade to hibernate 5.2 due to hibernate search which I know isn't supported, but we're trying incrementally roll out our major upgrades.

```java
java.lang.NoClassDefFoundError: org/hibernate/query/Query
    at repository.organization.OrganizationShareRepositoryTest.findAllByClientOrganizationAndStatusApproved(OrganizationShareRepositoryTest.java:82)
Caused by: java.lang.ClassNotFoundException: org.hibernate.query.Query
    at repository.organization.OrganizationShareRepositoryTest.findAllByClientOrganizationAndStatusApproved(OrganizationShareRepositoryTest.java:82) 
```

```java
public interface OrganizationShareRepository
    extends PagingAndSortingRepository<OrganizationShare, Long>, Saver<OrganizationShare> {    /**
     * you probably want to pass the same thing twice to get an either/or effect
     *
     * @param client
     * @param performing
     * @return
     */
    List<OrganizationShare> findAllByClientOrganizationOrPerformingOrganization(
        Organization client,
        Organization performing );    Stream<OrganizationShare> findAllByClientOrganizationAndStatus(
        Organization client,
        OrganizationShareStatusType status
    );    @Transactional( readOnly = true )
    default Collection<Long> findPerformingOrgsByClientWithStatusApproved( Organization client ) {
        return findAllByClientOrganizationAndStatus( client, OrganizationShareStatusType.APPROVED )
            .map( OrganizationShare::getPerformingOrganization )
            .map( Identifiable::getId )
            .collect( Collectors.toSet() );
    }    @Query( "select new com.mckesson.dex.projection.OrganizationShareProjectionImpl("
        + "s.performingOrganization.id, "
        + "s.performingOrganization.name, "
        + "s.clientOrganization.id, "
        + "s.clientOrganization.name, "
        + "s.dateModified) "
        + "from OrganizationShare s where s.status = "
        + "?#{T(com.mckesson.dex.model.principal.OrganizationShareStatusType).PENDING}"
        + " order by s.performingOrganization.name" )
    Page<OrganizationShareProjection> findAllPendingOrganizationShares( Pageable pageable );
    @Query( "select count(1) "
        + "from OrganizationShare s where s.status = "
        + "?#{T(com.mckesson.dex.model.principal.OrganizationShareStatusType).PENDING}"
        + " and s.performingOrganization.id = :activeOrganizationId " )
        Long countPendingOrganizationShares(         
            @Param( "activeOrganizationId" ) Long activeOrganizationId );
} 
```

```java
@Test
public void findAllByClientOrganizationAndStatusApproved() {        Organization org1 = mbf().standaloneLab().get();
    Organization org2 = mbf().standaloneLab().get();        OrganizationShareTestEntityBuilder share = mbf().organizationShare().setClientLab( org1 );
    mbf().organizationShare().setClientLab( org2 ).setStatus( OrganizationShareStatusType.APPROVED ).get();        Set<Long> expected = new HashSet<>();
    expected.add(
        share.setStatus( OrganizationShareStatusType.APPROVED ).get().getPerformingOrganization().getId()
    );
    for ( OrganizationShareStatusType statusType : OrganizationShareStatusType.values() ) {
        OrganizationShare organizationShare = share.setStatus( statusType ).get();
        if ( statusType == OrganizationShareStatusType.APPROVED ) {
            expected.add( organizationShare.getPerformingOrganization().getId() );
        }
    }
    log().info( "START TEST" );
    Collection<Long> approved = repo.findPerformingOrgsByClientWithStatusApproved( org1 ); // 82
    assertThat( approved, hasSize( 2 ) );
    assertThat( approved, containsInAnyOrder( expected.toArray() ) );        long count = repo.countPendingOrganizationShares( org1.getId() );
    assertThat( count, is( 0L ) );
    count = repo.countPendingOrganizationShares( org2.getId() );
    assertThat( count, is( 0L ) );
} 
```

---

**Affects:** 2.0.7 (Kay SR7)

**Comment by gregturn** [comment]
Considering we have https://github.com/spring-projects/spring-data-commons/wiki/ to track various key updates in the various modules amidst all the release trains, I'm closing this issue.
