### ISSUE TITLE
Issue with interface projection for a native postgres query [DATAJPA-1482]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#1798]
**[Thomas Lang](https://jira.spring.io/secure/ViewProfile.jspa?name=thomas.lang@th-deg.de)** opened **[DATAJPA-1482](https://jira.spring.io/browse/DATAJPA-1482?redirect=false)** and commented

I have this repository:

```java
public interface IRentalRepository extends CrudRepository<Rental, Long> {

    @Query(value = "select r.returndate as returnDate from rental r where r.returndate >= ?1 order by r.returndate asc limit 1", nativeQuery = true)
    RentalProjection findsMostRecentReturnDateAndTimeRankByLaboratory(LocalDate localDate);

    @Query(value = "select r.returndate as returnDateNative from rental r where r.returndate >= ?1 order by r.returndate asc limit 1", nativeQuery = true)
    RentalProjection findsMostRecentReturnDateNativeAndTimeRankByLaboratory(LocalDate localDate);

}
```

I have this projection interface:

```java
public interface RentalProjection {
    LocalDate getReturnDate();

    String getReturnDateNative();

}
```

Both queries do run indeed, but if i want to access the property

```java
LocalDate getReturnDate();
```

it (hibernate/spring data jpa) gives me the following exception:

```java
java.lang.IllegalArgumentException: Projection type must be an interface!
```

When i´m accessing the property

```java
String getReturnDateNative();
```

everything is fine.

I don´t really know if this is even Spring Data JPA related?  
Maybe you could check this out?  
Please see this repository with all the tests in it to show the case:  
https://github.com/THD-Thomas-Lang/projection-issue

Thank you for your help and work!  
Your greatest fan from lower bavaria :)  
Thomas

Please see here the stack trace:

```java
java.lang.IllegalArgumentException: Projection type must be an interface!

	at org.springframework.util.Assert.isTrue(Assert.java:118)
	at org.springframework.data.projection.ProxyProjectionFactory.createProjection(ProxyProjectionFactory.java:100)
	at org.springframework.data.projection.SpelAwareProxyProjectionFactory.createProjection(SpelAwareProxyProjectionFactory.java:45)
	at org.springframework.data.projection.ProjectingMethodInterceptor.getProjection(ProjectingMethodInterceptor.java:131)
	at org.springframework.data.projection.ProjectingMethodInterceptor.invoke(ProjectingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.ProxyProjectionFactory$TargetAwareMethodInterceptor.invoke(ProxyProjectionFactory.java:245)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:59)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy101.getReturnDate(Unknown Source)
	at de.thd.issue.IssueApplicationTests.issueShowCaseFailing(IssueApplicationTests.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

---

**Affects:** 2.1.3 (Lovelace SR3)

**Reference URL:** https://github.com/THD-Thomas-Lang/projection-issue

**Issue Links:**
- [DATACMNS-1452](https://jira.spring.io/browse/DATACMNS-1452) Make the ConversionsService used in ProjectingMethodInterceptor configurable
 (_**"depends on"**_)

**Comment by schauder** [comment]
Can you please retest with the latest milestone?

**Comment by gregturn** [comment]
Closing this since the apparent issue is improper types in the project interface.
