### ISSUE TITLE
Interface projection with native query not working for boolean (mysql) [DATACMNS-1695]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#2143]
**[Michal Ondrovic](https://jira.spring.io/secure/ViewProfile.jspa?name=anaq)** opened **[DATACMNS-1695](https://jira.spring.io/browse/DATACMNS-1695?redirect=false)** and commented

Simplified test case:

Projection interface:

```java
public interface TestDto {
 Long getId();
 Boolean getTest();
}
```

Query with projection:

```java
@Query(value = "select 1 id, true test", nativeQuery = true)
List<TestDto> test();
```

Boolean property "test" is not recognized as Boolean but as Byte. Calling getTest() throws this exception:

java.lang.IllegalArgumentException: Projection type must be an interface!

The projection is working if the boolean field is selected directly from a table, but not, when the field is "calculated".

More workarounds are possible, in my case change "Boolean getTest()" to "Byte getTest()" is the best

---

**Affects:** 2.2.6 (Moore SR6)

**Comment by mp911de** [comment]
We should improve the error message to report the actual issue. We don't want to make any assumptions over `Byte` to `Boolean` conversion as one could use `-1`, `0`, or `1` as `true` and we don't want to get into that business. Another approach to make it work, you could cast the value into a type that is reported by the driver to Java boolean (or one that can be safely converted to `Boolean`).

**Comment by mp911de** [comment]
Stack trace: 

```
java.lang.IllegalArgumentException: Projection type must be an interface!
	at org.springframework.util.Assert.isTrue(Assert.java:121) ~[spring-core-5.3.4-20210202.131018-48.jar:5.3.4-SNAPSHOT]
	at org.springframework.data.projection.ProxyProjectionFactory.createProjection(ProxyProjectionFactory.java:108) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.data.projection.SpelAwareProxyProjectionFactory.createProjection(SpelAwareProxyProjectionFactory.java:45) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.data.projection.ProjectingMethodInterceptor.getProjection(ProjectingMethodInterceptor.java:160) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.data.projection.ProjectingMethodInterceptor.potentiallyConvertResult(ProjectingMethodInterceptor.java:108) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.data.projection.ProjectingMethodInterceptor.invoke(ProjectingMethodInterceptor.java:85) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4-20210202.131018-48.jar:5.3.4-SNAPSHOT]
	at org.springframework.data.projection.ProxyProjectionFactory$TargetAwareMethodInterceptor.invoke(ProxyProjectionFactory.java:253) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4-20210202.131018-48.jar:5.3.4-SNAPSHOT]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.5.0-20210202.135327-181.jar:2.5.0-SNAPSHOT]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.4-20210202.131018-48.jar:5.3.4-SNAPSHOT]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) ~[spring-aop-5.3.4-20210202.131018-48.jar:5.3.4-SNAPSHOT]
```

The offending value is `BigInteger`. We could throw an exception that we cannot return the value or create a projection for the value %s of type %s that should be returned as %s.

**Comment by mp911de** [comment]
Moving the issue back to Spring Data Commons as `ProxyProjectionFactory` comes from there.
