### ISSUE TITLE
Issue with interface projection for a native informix query

### ISSUE THREAD

**Issue by sgflt** [spring-projects/spring-data-jpa#2157]
Assume following interface:

```java
interface ProjectionObject {
    CustomTypeObject getCustomType();
}
```

and use case:
```java
var projection = this.repository.findMyProjectionObject();
projection.getCustomType() // 2.2.10 OK, 2.4.2+ does not work
```

Converter:
```java
@Converter
public class CustomTypeObjectConverter implements  javax.persistence.AttributeConverter<CustomTypeObject, String> {

  @Override
  public String convertToDatabaseColumn(final CustomTypeObject attribute) {
    return attribute == null ? null : attribute.get();
  }


  @Override
  public CustomTypeObject convertToEntityAttribute(final String dbData) {
    return new  CustomTypeObject(dbData);
  }
}
```

Repository:
```java
interface CustomObjectRepository extends JpaRepository<CustomObjectEntity, Long> {
  @Query(value = "SELECT FIRST 1 'data' as customType FROM systables", nativeQuery = true)
  CustomObjectType findMyProjectionObject();
}
```

Entity 
```java
@Entity
@Table(name = "systables")
class CustomObjectEntity {
  @Column(name = "tabname")
  @Convert(converter = CustomTypeObjectConverter.class)
  private CustomTypeObject code;
  
  public CustomTypeObject getCustomType() {
    return this.code;
  }
}
```

With defined javax.persistence.AttributeConverter<CustomTypeObject, String> in Spring 2.2.10 return value was converted without problem.

In spring Boot 2.4.2 and 2.4.3 conversion throws:
<details>

```
java.lang.IllegalArgumentException: Projection type must be an interface!
	at org.springframework.util.Assert.isTrue(Assert.java:121)
	at org.springframework.data.projection.ProxyProjectionFactory.createProjection(ProxyProjectionFactory.java:108)
	at org.springframework.data.projection.SpelAwareProxyProjectionFactory.createProjection(SpelAwareProxyProjectionFactory.java:45)
	at org.springframework.data.projection.ProjectingMethodInterceptor.getProjection(ProjectingMethodInterceptor.java:160)
	at org.springframework.data.projection.ProjectingMethodInterceptor.potentiallyConvertResult(ProjectingMethodInterceptor.java:108)
	at org.springframework.data.projection.ProjectingMethodInterceptor.invoke(ProjectingMethodInterceptor.java:85)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.ProxyProjectionFactory$TargetAwareMethodInterceptor.invoke(ProxyProjectionFactory.java:253)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
```
</details>

Issue is related  to https://github.com/spring-projects/spring-data-jpa/issues/1798 and https://github.com/spring-projects/spring-data-commons/issues/2260.

Caused probably by https://github.com/spring-projects/spring-data-commons/pull/459 when Object to Object mapping has been removed.

```java
CONVERSION_SERVICE.removeConvertible(Object.class, Object.class);
```

**Comment by sgflt** [comment]
Also may be related to https://github.com/spring-projects/spring-data-jpa/issues/2058

**Comment by schauder** [comment]
We don't intend to support arbitrary conversions for projections.

It was working just by accident in previous versions. Sorry for that.
