### ISSUE TITLE
Is this a bug or incorrect use

### ISSUE THREAD

**Issue by Alceatraz** [spring-projects/spring-data-jpa#2160]
Set up demo:

Using spring-boot 2.4.2 and hibernate-spatial 5.4.28 with mysql 8

The application config
```properties
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
spring.jpa.database-platform=org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
```

The entity
```java
import org.geolatte.geom.Geometry;
import org.geolatte.geom.Point;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "demo", schema = "jpa-test")
public class DemoEntity {

    @Id
    @GeneratedValue
    @Column(name = "id", unique = true, nullable = false)
    private Long id;

    @Column(name = "address_1", columnDefinition = "geometry") private Geometry<?> address;
    @Column(name = "address_2", columnDefinition = "point") private Point<?> center;

}
```

The repository

```java
import com.example.demo.module.DemoEntity;
import org.springframework.data.jpa.repository.JpaRepository;

public interface DemoRepository extends JpaRepository<DemoEntity, Long> {

}
```

The runner

```java
import com.example.demo.module.DemoEntity;
import com.example.demo.repository.DemoRepository;
import org.geolatte.geom.Geometry;
import org.geolatte.geom.Point;
import org.geolatte.geom.codec.Wkt;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.stereotype.Component;

@Component
public class DemoRunner implements ApplicationRunner {

    private final DemoRepository demoRepository;

    @Autowired
    public DemoRunner(DemoRepository demoRepository) {
        this.demoRepository = demoRepository;
    }

    @Override
    public void run(ApplicationArguments args) {
        DemoEntity entity = new DemoEntity();
        Geometry<?> geometry = Wkt.fromWkt("point(115 35)");
        entity.setAddress(geometry);
        if (geometry instanceof Point) entity.setCenter((Point<?>) geometry);
        demoRepository.saveAndFlush(entity);
    }
}
```

Then the first boot will create those tables:

```log
Hibernate: drop table if exists demo
Hibernate: drop table if exists hibernate_sequence
Hibernate: create table demo (id bigint not null, address_1 geometry, address_2 point, primary key (id)) engine=InnoDB
Hibernate: create table hibernate_sequence (next_val bigint) engine=InnoDB
Hibernate: insert into hibernate_sequence values ( 1 )
```

And show create table:

```sql
CREATE TABLE `demo` (
  `id` bigint NOT NULL,
  `address_1` geometry DEFAULT NULL,
  `address_2` point DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

Change application config to:
```properties
spring.jpa.hibernate.ddl-auto=validate
```

Run it again:

```log
Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [address_2] in table [jpa-test.demo]; found [geometry (Types#BINARY)], but expecting [point (Types#ARRAY)]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateColumnType(AbstractSchemaValidator.java:159) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.validateTable(AbstractSchemaValidator.java:143) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.tool.schema.internal.GroupedSchemaValidatorImpl.validateTables(GroupedSchemaValidatorImpl.java:42) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.performValidation(AbstractSchemaValidator.java:89) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.tool.schema.internal.AbstractSchemaValidator.doValidation(AbstractSchemaValidator.java:68) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:192) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:73) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:316) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:469) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1259) ~[hibernate-core-5.4.27.Final.jar:5.4.27.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58) ~[spring-orm-5.3.3.jar:5.3.3]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.3.3.jar:5.3.3]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[spring-orm-5.3.3.jar:5.3.3]
	... 20 common frames omitted
```

**Comment by schauder** [comment]
This sounds like a bug to me, but a Hibernate bug. Spring doesn't really do anything with the schema creation except triggering it.

Please, raise an issue on the Hibernate issue tracker using a reproducer not using Spring. Understandably they want to avoid working on issues that turn out to be caused by Spring. 

If against expectation the issue can't be reproduced without Spring please provide a reproducer here.
