### ISSUE TITLE
Able to use custom methods in repository. But default methods like findall(), save() are not working.

### ISSUE THREAD

**Issue by writemail2nawaz** [spring-projects/spring-data-jpa#2250]
```
package com.company.entity;

import java.math.BigInteger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Table(name = "EMPLOYEE_TB")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Employee {

	@Id
	@Column(name = "EMP_ID")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private BigInteger empId;

	@Column(name = "EMP_NAME")
	private String empName;

}
```

```
package com.company.rtls.repository;

import java.math.BigInteger;
import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import com.company.rtls.entity.Employee;

@Repository
public interface EmployeeRepo extends JpaRepository<Employee, BigInteger> {

}
```

```
package com.company.service;


import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import com.company.entity.Employee;

@Service
public class UpdateAnfasEmp {

	private static final Logger logger = LoggerFactory.getLogger(UpdateAnfasEmp.class);
	
	@Autowired
	private EmployeeRepo employeeRepo;
	
	@Scheduled(cron = "0 0 6,19 * * *")
	public void updateEmpScheduler() {
		updateEmpFromAPI();
	}
public void updateEmpFromAPI() {
		new Thread() {
			public void run(){
				
				try {
List<Employee> empList = employeeRepo.findAll();
				
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		}.start();
		
	}
}
```

**Comment by writemail2nawaz** [comment]
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.detectPersistenceExceptionTranslators(PersistenceExceptionTranslationInterceptor.java:167)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
        at com.sun.proxy.$Proxy98.findAll(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)2021-06-26 16:49:25.350  INFO 9180 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.

**Comment by schauder** [comment]
This seems to be a usage question. Please ask those over at StackOverflow where others can help answering them and where others can better find the answers.

In any case please include the complete stack trace.
