### ISSUE TITLE
Cannot create a Repository class with a EmbeddedId and relations

### ISSUE THREAD

**Issue by MelleD** [spring-projects/spring-data-jpa#2271]
I am currently trying to use an Embedded ID together with spring data. However, the repository cannot be created because too many ID attributes are found. 
Foo and bar are also identified as PK candidates. But it shouldn't, because MapsId is set.

Example for a many to many relation entity.

```
@Entity
public class FooBar  {

   @EmbeddedId
   private FooBarId id = new FooBarId();

   @ManyToOne
   @JoinColumn( name = "foo_id" )
   @MapsId( "fooId" )
   private Foo foo;

   @ManyToOne
   @JoinColumn( name = "bar_id")
   @MapsId( "barId" )
   private Bar bar;

}

```

```
@Embeddable
public class FooBarId implements Serializable {

   @Column( name = "foo_id" )
   private Long fooId;

   @Column( name = "bar_id")
   private Long barId;

}
```

`interface FooBarRepository extends JpaRepository<FooBar, FooBarId>`

```
error
   caused by: java.lang.IllegalArgumentException: Expected id attribute type [class FooBarId] on the existing id attribute [SingularAttributeImpl[EntityTypeImpl@1957315654:Bar [ javaType: class Bar descriptor: RelationalDescriptor(Bar --> [DatabaseTable(bar)]), mappings: 4],org.eclipse.persistence.mappings.ManyToOneMapping[bar]]] on the identifiable type [EntityTypeImpl@1325241326:FooBar [ javaType: class FooBar descriptor: RelationalDescriptor(FooBar --> [DatabaseTable(foo_bar)]), mappings: 5]] but found attribute type [class Bar].
      at org.eclipse.persistence.internal.jpa.metamodel.IdentifiableTypeImpl.getId(IdentifiableTypeImpl.java:206) ~[org.eclipse.persistence.jpa-2.7.8.jar:na]
      at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation$IdMetadata.<init>(JpaMetamodelEntityInformation.java:271) ~[spring-data-jpa-2.5.3.jar:2.5.3]
      at org.springframework.data.jpa.repository.support.JpaMetamodelEntityInformation.<init>(JpaMetamodelEntityInformation.java:89) ~[spring-data-jpa-2.5.3.jar:2.5.3]
      at org.springframework.data.jpa.repository.support.JpaEntityInformationSupport.getEntityInformation(JpaEntityInformationSupport.java:66) ~[spring-data-jpa-2.5.3.jar:2.5.3]
      at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getEntityInformation(JpaRepositoryFactory.java:228) ~[spring-data-jpa-2.5.3.jar:2.5.3]
      at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:178) ~[spring-data-jpa-2.5.3.jar:2.5.3]
      at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:161) ~[spring-data-jpa-2.5.3.jar:2.5.3]
      at org.springframework.data.jpa.repository.support.JpaRepositoryFactory.getTargetRepository(JpaRepositoryFactory.java:72) ~[spring-data-jpa-2.5.3.jar:2.5.3]
```

I found the issue on the `JpaMetamodelEntityInformation`
```
    this.attributes = (Set<SingularAttribute<? super T, ?>>) (source.hasSingleIdAttribute()
					? Collections.singleton(source.getId(source.getIdType().getJavaType()))

 ```

see https://github.com/eclipse-ee4j/eclipselink/issues/1228

Maybe there is good workaround?

EDIT: For example catch the IllegalArgumentException and try to solve the id attribute. Somthing like this

`source.getSingularAttribute( "id" ).isId() && getSingularAttribute( "id" ).getPersistentAttributeType().name().equals("EMBEDDED) && source.getSingularAttribute( "id" ).getJavaType() == source.getIdType().getJavaType()`

**Comment by schauder** [comment]
Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by MelleD** [comment]
@schauder here is a example https://github.com/MelleD/spring-data-eclipse-link-demo
With EclipseLink it is not working. With Hibernate it works

**Comment by MelleD** [comment]
Are there any ideas or workarounds here?

**Comment by schauder** [comment]
Judging from your description and the exception this seems to be an EclipseLink problem, that they don't provide the correct meta data for `getSingularAttribute`. 

I suggest raising a ticket with them. 
Do you agree?

**Comment by MelleD** [comment]
@schauder yes you are right. See above I already raised a ticket (posted the link). But I think EclipeLink will not fix this issue, so Iam looking for a workaround. I hope I have more luck here to find a solution

**Comment by MelleD** [comment]
Any news here?

**Comment by MelleD** [comment]
EclipseLinked fixed the bug
