### ISSUE TITLE
Add fluent `findBy` API to `JpaSpecificationExecutor`

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-data-jpa#2274]
follow up #2273, I need streaming matched data filter by `Specification`, I tried
```java
public interface UserRepository extends JpaRepository<User, Long>, JpaSpecificationExecutor<User> {

	Stream<User> streamAllBy(@Nullable Specification<User> spec, Sort sort);

}
```
It failed with:
```
org.springframework.dao.InvalidDataAccessApiUsageException: At least 1 parameter(s) provided but only 0 parameter(s) present in query.; nested exception is java.lang.IllegalArgumentException: At least 1 parameter(s) provided but only 0 parameter(s) present in query.
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:374)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:235)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:61)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at com.sun.proxy.$Proxy94.streamAllBy(Unknown Source)

```
It seems like `Specification` method parameter is treated as query parameter.

**Comment by schauder** [comment]
Related to #1752 spring-projects/spring-data-commons#2421

**Comment by gregturn** [comment]
@quaff Have you checked out the recently added `QuerydslJpaPredicateExecutor.findBy(Predicate predicate, Function<FetchableFluentQuery<S>, R> queryFunction)` yet?

An example of using it to get a `Stream` -based response based upon a Query DSL criteria is shown below. 

```java
@Test // GH-2294
void findByFluentPredicateStream() {

	Stream<User> userStream = predicateExecutor.findBy(user.firstname.contains("v"),
			q -> q.sortBy(Sort.by("firstname")).stream());

	assertThat(userStream).containsExactly(dave, oliver);
}
```

There is also support for Query By Example.

**Comment by quaff** [comment]
@gregturn Thanks, but I'm not using Query DSL.
