### ISSUE TITLE
NullPointerException for interface based projection

### ISSUE THREAD

**Issue by makigumo** [spring-projects/spring-data-jpa#2416]
Hello, after updating to the latest spring boot release 2.6.3 I'm met with the NullPointerException below.

The following change (https://github.com/spring-projects/spring-data-jpa/issues/2363 https://github.com/spring-projects/spring-data-jpa/commit/8cd1388318032ddcdeeeadf347f691ed3a03e583) seems to be the cause.

I'm using a simple recursive interface based projection with a query method, similar to Example 81 in https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#projections, which has worked until now.

```log
[..]
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInterface()" because "typeToRead" is null
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:181)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:152)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:59)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81)
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.isInterface()" because "typeToRead" is null
```

**Comment by Eng-Fouad** [comment]
I got the same error after upgrading to Spring boot 2.6.3.

**Comment by makigumo** [comment]
Closing, duplicate of https://github.com/spring-projects/spring-data-jpa/issues/2408
