### ISSUE TITLE
Unable to locate Attribute  with the the given name for field with one letter prefix

### ISSUE THREAD

**Issue by joannakotula** [spring-projects/spring-data-jpa#2440]
### Context
I'm trying to upgrade an old application to newest spring boot.

### Problem

In our application we use JpaRepository and query methods. One of entities has a field 'nStatus' and it causes an error: `java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [NStatus]`

### Reproduction
See small project: https://github.com/joannakotula/spring-data-jpa-bug

When trying to run I get an error:
```
Caused by: java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [NStatus] on this ManagedType [com.example.jpabug.data.Model]
	at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.checkNotNull(AbstractManagedType.java:148) ~[hibernate-core-5.6.4.Final.jar:5.6.4.Final]
	at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:119) ~[hibernate-core-5.6.4.Final.jar:5.6.4.Final]
	at org.hibernate.metamodel.model.domain.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:44) ~[hibernate-core-5.6.4.Final.jar:5.6.4.Final]
	at org.springframework.data.jpa.repository.query.QueryUtils.requiresOuterJoin(QueryUtils.java:705) ~[spring-data-jpa-2.6.1.jar:2.6.1]
```

### Affected version
Checked spring boot 2.2.0 and 2.6.3 - error occurs. First spring boot version with error: 2.1.9:
```
Caused by: java.lang.IllegalArgumentException: Unable to locate Attribute  with the the given name [NStatus] on this ManagedType [com.example.jpabug.data.Model]
	at org.hibernate.metamodel.internal.AbstractManagedType.checkNotNull(AbstractManagedType.java:128) ~[hibernate-core-5.3.12.Final.jar:5.3.12.Final]
	at org.hibernate.metamodel.internal.AbstractManagedType.getAttribute(AbstractManagedType.java:113) ~[hibernate-core-5.3.12.Final.jar:5.3.12.Final]
	at org.springframework.data.jpa.repository.query.QueryUtils.toExpressionRecursively(QueryUtils.java:633) ~[spring-data-jpa-2.1.11.RELEASE.jar:2.1.11.RELEASE]
	at org.springframework.data.jpa.repository.query.QueryUtils.toExpressionRecursively(QueryUtils.java:617) ~[spring-data-jpa-2.1.11.RELEASE.jar:2.1.11.RELEASE]
	at org
```

**Comment by joannakotula** [comment]
Found two other issues that may be linked:
#1247
#2318

**Comment by schauder** [comment]
This behaviour is due to the quirks of the Java Beans naming convention.

In order to convert from the `NStatus` you use in the query method to a property name we use https://docs.oracle.com/javase/8/docs/api/java/beans/Introspector.html#decapitalize-java.lang.String-

The JavaDoc states: 

> Utility method to take a string and convert it to normal Java variable name capitalization. This normally means converting the first character from upper case to lower case, but in the (unusual) special case when there is more than one character and both the first and second characters are upper case, we leave it alone.
Thus "FooBah" becomes "fooBah" and "X" becomes "x", but "URL" stays as "URL".

Applied to `NStatus` this results in `NStatus` so the property name Spring Data is  looking for is just that and that should be the name of your field.

I highly recommend to avoid single lower case or multiple uppercase letters at the beginning of property/field names.
