### ISSUE TITLE
DataIntegrityViolationException is thrown instead of returning empty result for select query method

### ISSUE THREAD

**Issue by hanct** [spring-projects/spring-data-jpa#2463]
Spring Boot： 2.6.4

I have a repository interface as shown below, with my custom query method
```
interface IHeroRepo extends CrudRepository<HeroEntity, String>{
		Optional<HeroEntity> findByName(String name);
}
```
In my service class, i call this repository as shown below
```
     heroRepo.findByName("test");  //no record with name="test"  exist in db2. So it return Optional.empty, which is as expected.
     heroRepo.findByName("test1111111111111111111"); //test1111... does not exist in db2. And it throws DataIntegrityViolationException, which is not what I expect.
```
I notice that the above differences occur, is because my HeroEnity's associated DB table's  name field is set to CHARACTERS(4) in the DB.    
Since “test" adhere to the db2 table field schema (it is equal or less than the field size),  it simply return Optional.empty.
But cos "test1111111..." violates the schema, it throws exception. This caught me by surprise, since I am doing a select, not update or insert.  

What should I do, if I do NOT want **DataIntegrityViolationException** to be thrown for such select query method, since I prefer that it returns Optional.empty . This is similar to me doing native sql select ("select * from HERO_TBL where name="test111111111111111"), and i would get empty result set, rather than getting an exception.

**Comment by quaff** [comment]
Could you paste the full error stack trace?

**Comment by schauder** [comment]
This sounds like a JPA/DB2 problem, not a Spring Data JPA one to me.

If you disagree, please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

A possible workaround could be to 

a) change the column do `VARCHAR` or similar

b) provide a custom query, providing the necessary conversion.

Both workaround assume that the problem actually is DB2 trying to convert the argument to `CHARACTERS(4)`

**Comment by hanct** [comment]
> Could you paste the full error stack trace?
Below is the requested full error stack trace.  As the codebase is confidential, hence i have replaced some of the program class names with random letter, but i think that should not impact the analysis

```
2022-03-15 20:29:01 - o.h.e.jdbc.spi.SqlExceptionHelper - SQL Error: -302, SQLState: 22001
2022-03-15 20:29:01 - o.h.e.jdbc.spi.SqlExceptionHelper - DB2 SQL Error: SQLCODE=-302, SQLSTATE=22001, SQLERRMC=null, DRIVER=4.31.10
org.springframework.dao.DataIntegrityViolationException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not extract ResultSet
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:280)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215)
	at jdk.proxy2/jdk.proxy2.$Proxy114.findByDivTxt(Unknown Source)
	at sg.zzzzzzzzzzzzzzzzzzzzzzzzzzz(yyyyyyyyyyy.java:378)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$$FastClassBySpringCGLIB$$e9ce2827.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:698)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxService$$EnhancerBySpringCGLIB$$b5902320.removeGroup(<generated>)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(yyyyyy.java:223)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(yyyyyy.java:508)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(yyyyy.java:480)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(yyyyyy.java:290)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(yyyyy.java:166)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx(yyyyyyyyy.java:106)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:310)
	at sg.xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxApplication.main(yyyyyy.java:23)
Caused by: org.hibernate.exception.DataException: could not extract ResultSet
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:52)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:67)
	at org.hibernate.loader.Loader.getResultSet(Loader.java:2322)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2075)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2037)
	at org.hibernate.loader.Loader.doQuery(Loader.java:956)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:357)
	at org.hibernate.loader.Loader.doList(Loader.java:2868)
	at org.hibernate.loader.Loader.doList(Loader.java:2850)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2682)
	at org.hibernate.loader.Loader.list(Loader.java:2677)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:540)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1454)
	at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1649)
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1617)
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1665)
	at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:198)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:155)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:143)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:159)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:138)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	... 30 more
Caused by: com.ibm.db2.jcc.am.SqlDataException: DB2 SQL Error: SQLCODE=-302, SQLSTATE=22001, SQLERRMC=null, DRIVER=4.31.10
	at com.ibm.db2.jcc.am.b7.a(b7.java:802)
	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
	at com.ibm.db2.jcc.am.b7.a(b7.java:140)
	at com.ibm.db2.jcc.am.k_.c(k_.java:2844)
	at com.ibm.db2.jcc.am.k_.a(k_.java:2281)
	at com.ibm.db2.jcc.t4.ab.r(ab.java:1670)
	at com.ibm.db2.jcc.t4.ab.l(ab.java:754)
	at com.ibm.db2.jcc.t4.ab.d(ab.java:110)
	at com.ibm.db2.jcc.t4.p.c(p.java:44)
	at com.ibm.db2.jcc.t4.av.j(av.java:162)
	at com.ibm.db2.jcc.am.k_.an(k_.java:2276)
	at com.ibm.db2.jcc.am.la.a(la.java:4699)
	at com.ibm.db2.jcc.am.la.b(la.java:4215)
	at com.ibm.db2.jcc.am.la.a(la.java:4860)
	at com.ibm.db2.jcc.am.la.b(la.java:4215)
	at com.ibm.db2.jcc.am.la.bd(la.java:785)
	at com.ibm.db2.jcc.am.la.executeQuery(la.java:750)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.extract(ResultSetReturnImpl.java:57)
	... 61 more
```

**Comment by hanct** [comment]
> This sounds like a JPA/DB2 problem, not a Spring Data JPA one to me.
> 
> If you disagree, please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).
> 
> A possible workaround could be to
> 
> a) change the column do `VARCHAR` or similar
> 
> b) provide a custom query, providing the necessary conversion.
> 
> Both workaround assume that the problem actually is DB2 trying to convert the argument to `CHARACTERS(4)`

I also suspect could be JPA/DB2, but not 100% sure. That is y i first post this question here just to see if anyone has encounter such problem, and hence could share their finding.   If confirm not Spring Data JPA issue, I will close this case.
Do note that i have also tried 'VARCHAR', same issue.

Below is what i try:
I define a spring data repository interface, as shown below
(note:  divTxt field of the MyEntity map to a column in my db table whose varchar is 50
```
public interface ITestRepos extends  JpaSpecificationExecutor<MyEntity>,PagingAndSortingRepository<MyEntity, String>{
	public Optional<MyEntity> findByDivTxt(String d);
}
```

Then i do the below, which throw the exception. See the above reply which shows my error stack trace
```
@Autowired
ITestRepos testRepos;
var o = this.testRepos.findByDivTxt("011111111112222222222333333333344444444445555555555"); //51 characters
```
But when i remove one character in the string argument of the findByDivTxt, so that it is 50 characters (equal to the column varchar max length of 50), no error thrown, it just returns Optional.Empty instead of throwing DataIntegrityViolationException.

**Comment by schauder** [comment]
This confirms this is a weird behaviour of DB2: https://forum.hibernate.org/viewtopic.php?p=2403724

If something should work around that it would be the task of the JPA implementation.
