### ISSUE TITLE
` is not added to the table name when the table name is a reserved word

### ISSUE THREAD

**Issue by mikoto2464** [spring-projects/spring-data-jpa#2517]
When the table name is "order" a reserved word, I use the `<S extends T> S save(S entity)` method in `JpaRepository<T, ID>`.
This exception occurred:
```
Caused by: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'order=0, page_count=2, patch_time='2022-05-02 00:01:49.428', previous_artwork_id' at line 1
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1098) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1046) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1371) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1031) ~[mysql-connector-java-8.0.28.jar:8.0.28]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.6.4.Final.jar:5.6.4.Final]
	... 65 common frames omitted
```

But when I rename the `order` column to `artwork_order` then this exception doesn't appear.
So I think this exception is thrown here because the table name is not surrounded by the ` symbol to distinguish reserved words from the table name.

**Comment by s-sathish** [comment]
Hi Mikoto,
In your entity definition, you can use something like this -
<img width="180" alt="Screenshot 2022-05-02 at 2 07 18 PM" src="https://user-images.githubusercontent.com/41979412/166207547-8cb41684-aa8c-4d2a-ad8e-be1f27b67832.png">

Same applies when you are using a reserved keyword for table column name -
<img width="223" alt="Screenshot 2022-05-02 at 2 09 38 PM" src="https://user-images.githubusercontent.com/41979412/166207698-977c3e7a-cce4-44fd-9e6f-e892330a5ab6.png">

**Comment by schauder** [comment]
This the behaviour of JPA and not under the control of Spring Data JPA.
