### ISSUE TITLE
Add native support for spring-data-envers

### ISSUE THREAD

**Issue by ch4mpy** [spring-projects/spring-data-jpa#2662]
As requested by @snicoll , I'm moving [this issue](https://github.com/spring-projects-experimental/spring-native/issues/1016) here.

It would be great to have a complete working sample with an `@Audited` `@Entity` associated with a `RevisionRepository` in an application with `@EnableEnversRepositories`, and having instruction to build a running native image.

**Comment by christophstrobl** [comment]
@ch4mpy Thanks for creating the issue! I've created oracle/graalvm-reachability-metadata#82 to provide missing metadata for _hibernate-envers_. Once that's in place we will continue here with the missing bits from data spring-data side.

**Comment by Map** [comment]
> @ch4mpy Thanks for creating the issue! I've created [oracle/graalvm-reachability-metadata#82](https://github.com/oracle/graalvm-reachability-metadata/issues/82) to provide missing metadata for _hibernate-envers_. Once that's in place we will continue here with the missing bits from data spring-data side.

Hi! Is this issue still in progress? The metadata issue in the graalvm repo seems to be closed and afaik this issue here can be unblocked :)

**Comment by joaquimvila** [comment]
Any news regarding this?

**Comment by korkutkose** [comment]
Any updates on this? There are services we would like to migrate into spring-native to reduce resource foot prints but almost all of our services are depending on envers. I honestly don't want to reinvent the wheel and implement my own solution for basic auditing needs. A small heads up would be sufficient about the progress :)

**Comment by TimSin** [comment]
We'd also like our existing services to use native images, but this issue is a blocker for us. Has there been any progress on it?

**Comment by stefferro** [comment]
Hi, do you have any update on this ?

**Comment by hangedfish** [comment]
SpringBoot 4.0.1 with GraalVM 25.0.2 still not work

```
Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Could not locate field name [timestamp] on class [org.hibernate.envers.DefaultRevisionEntity]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1817)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:603)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:525)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:371)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:331)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:201)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:976)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:620)
	at org.springframework.boot.web.server.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:756)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:445)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:321)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at com.ztgame.safe.auth.AuthApplication.main(AuthApplication.java:16)
	at java.base@25.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
```

**Comment by christophstrobl** [comment]
@hangedfish thank you for the heads up on the issue - the error seems to stem from missing [GraalVM reachability metadata](https://github.com/oracle/graalvm-reachability-metadata/tree/master/metadata/org.hibernate.orm/hibernate-envers) for `org.hibernate.envers.RevisionMapping`. Hibernate [moved some fields around](https://github.com/hibernate/hibernate-orm/commit/e06da88b4226cee14f7eb17e2217bafcc39a04f0) rendering the existing metadata insufficient. 
Please reach out to the [GraalVM team](https://github.com/oracle/graalvm-reachability-metadata/issues) and to check and update the metadata for envers.
