### ISSUE TITLE
Native query regression trying spring boot 3

### ISSUE THREAD

**Issue by Polve** [spring-projects/spring-data-jpa#2680]
I'm trying to upgrade to the latest spring boot 3 RC in order to check if something breaks.
The only problems turned out to be in spring JPA, here is one (simple to fix for me).

This query stopped working:
```
@Query(nativeQuery = true,
value = "SELECT DISTINCT x.label FROM txinfo_label x WHERE x.txinfo_id in (SELECT id from txinfo y WHERE y.account = ?1)")
List<String> findLabelsByAccount(CmAccount account);
```

With this runtime error:
```
Caused by: java.lang.IllegalArgumentException: Could not resolve NativeQuery parameter type : `org.hibernate.query.internal.QueryParameterPositionalImpl@20`
        at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerNativeQueryParameters(JdbcParameterBindings.java:142) ~[hibernate-core-6.1.4.Final.jar:6.1.4.Final]
        at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:82) ~[hibernate-core-6.1.4.Final.jar:6.1.4.Final]
        at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:596) ~[hibernate-core-6.1.4.Final.jar:6.1.4.Final]
        at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363) ~[hibernate-core-6.1.4.Final.jar:6.1.4.Final]
        at org.hibernate.query.Query.getResultList(Query.java:94) ~[hibernate-core-6.1.4.Final.jar:6.1.4.Final]
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:127) ~[spring-data-jpa-3.0.0-RC1.jar:3.0.0-RC1]
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90) ~[spring-data-jpa-3.0.0-RC1.jar:3.0.0-RC1]
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148) ~[spring-data-jpa-3.0.0-RC1.jar:3.0.0-RC1]
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136) ~[spring-data-jpa-3.0.0-RC1.jar:3.0.0-RC1]
```

The problem is easily fixed changing the signature of the method this way:
```
List<String> findLabelsByAccount(int accountId);
```
Anyway I open an issue over it because it seems like a regression.

**Comment by schauder** [comment]
What does "stopped working" mean exactly?

**Comment by Polve** [comment]
I'm sorry: I forgot to attach the stack trace, I updated the issue with the missing information.

**Comment by schauder** [comment]
This sounds like an Hibernate 6 issue. I would suspect that when you run a native query directly with Hibernate (without Spring) with an entity as an argument it would stop working with Hibernate 6.

Could you verify that, and otherwise provide a reproducer please.

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by Polve** [comment]
I tried to setup a minimal project to reproduce the problem but since the DB structure is quite complex I was not able in the allowed time, sorry.

Since the fix is trivial I would consider this just a bit more than a nuisance, so I close it.

Thanks anyway for the prompt support.

**Comment by Illutax** [comment]
> Confirm, native queries in JPA repositories don't work if you use a hibernate entity as a parameter. (Hibernate 6.4.0)

Or an embeddable as a parameter.

**Comment by borjaevo** [comment]
I am interested to know if it will like this forever (like a functionality change) or will be fixed.
