### ISSUE TITLE
JPA Hibernate float value not taking from @Column precision

### ISSUE THREAD

**Issue by rayman245** [spring-projects/spring-data-jpa#2684]
Hi I am getting this error when trying to generate DDL from Entity, only occurring for Double values with precision 53.

```
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table <table> (value float(177))" via JDBC Statement
.
.
org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.0-RC1.jar:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.0-RC1.jar:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.0-RC1.jar:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.0-RC1.jar:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.0-RC1.jar:3.0.0-RC1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.0-RC1.jar:3.0.0-RC1]
	at com.Application.main(Application.java:8) ~[classes/:na]
Caused by: org.postgresql.util.PSQLException: ERROR: precision for type float must be less than 54 bits
```

As shown here the generated entity (From JOOQ) has the correct precision 53,
![image](https://user-images.githubusercontent.com/11938827/197714596-3e90f751-1279-4551-a124-bf2593fa5949.png)

All double precision seems to be translating to 177 bits instead of using the defined 53 bits. We are trying to upgrade from Spring-Boot v2 to v3.

**Comment by rayman245** [comment]
Thanks for the heads up @schauder.
Created ticket with Hibernate -> https://hibernate.atlassian.net/browse/HHH-15623
