### ISSUE TITLE
org.hibernate.jpa.TypedParameterValue cannot be cast to class java.util.Date

### ISSUE THREAD

**Issue by edudar** [spring-projects/spring-data-jpa#2695]
There are a few related issues: https://github.com/spring-projects/spring-data-jpa/issues/2548, https://github.com/spring-projects/spring-data-jpa/issues/2570, etc.

It does not seem to work with nullable temporal parameters either. `QueryParameterSetter` casts `value` to `Date` explicitly. The actual type is `TypedParameterValue` since 2.7, though. This causes a standard class case exception like 
```
java.lang.ClassCastException: class org.hibernate.jpa.TypedParameterValue cannot be cast to class java.util.Date
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.lambda$setParameter$1(QueryParameterSetter.java:98)
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$ErrorHandling$1.execute(QueryParameterSetter.java:140)
	at org.springframework.data.jpa.repository.query.QueryParameterSetter$NamedOrIndexedQueryParameterSetter.setParameter(QueryParameterSetter.java:98)
```

**Comment by schauder** [comment]
Could you try this with a recent snapshot, to make sure it is still a problem?

**Comment by spring-projects-issues** [comment]
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-projects-issues** [comment]
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.
