### ISSUE TITLE
When the q class generated by querydsl and the entity class of jpa are not in the same package path, the q class cannot be found. spring boot <version>3.0.0-RC2</version>

### ISSUE THREAD

**Issue by mmm8955405** [spring-projects/spring-data-jpa#2703]
MyRepository extends JpaRepository<SysRoleResource, ?>,QuerydslPredicateExecutor<SysRoleResource>

Start and report an error：
Did not find a query class  QSysRoleResource for domain class SysRoleResource
at org.springframework.data.querydsl.SimpleEntityPathResolver.createPath(SimpleEntityPathResolver.java:78)

hope：
Provide spring configuration, support q class and jpa entity class under different packages

**Comment by mmm8955405** [comment]
Generate Q type week under the same path. 
The same problem is as follows:  2098
https://github.com/spring-projects/spring-data-jpa/issues/2708

After adding the javax. persistence api package, new problems are encountered:

`Caused by: java.lang.NoSuchMethodError: 'void com.querydsl.jpa.impl.JPAQuery.<init>(jakarta.persistence.EntityManager, com.querydsl.jpa.JPQLTemplates)'
	at org.springframework.data.jpa.repository.support.Querydsl.createQuery(Querydsl.java:85) ~[spring-data-jpa-3.0.0-RC2.jar:3.0.0-RC2]
	at org.springframework.data.jpa.repository.support.Querydsl.createQuery(Querydsl.java:102) ~[spring-data-jpa-3.0.0-RC2.jar:3.0.0-RC2]`
