### ISSUE TITLE
request for support of hibernate 5.6.x jakarta

### ISSUE THREAD

**Issue by robtha** [spring-projects/spring-data-jpa#2711]
using Hibernate 5.6.14 jakarta with spring-data-jpa 3.0.0 fails with 'java.lang.NoClassDefFoundError: org/hibernate/query/BindableType'

`HibernateJpaParametersParameterAccessor` only supports Hibernate 6.1.x.

It would be great if we could use Hibernate 5.6 jakarta version as this would us upgrading to spring-data-jpa 3.0.0 without upgrading/refactoring entity models.

Of course in the end we want to upgrade to Hibernate 6.1 too, but it would be helpful if this must have to be done in one step.

kind regards
robert

`
java.lang.NoClassDefFoundError: org/hibernate/query/BindableType
	at org.springframework.data.jpa.provider.PersistenceProvider$1.getParameterAccessor(PersistenceProvider.java:109)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.obtainParameterAccessor(AbstractJpaQuery.java:156)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:147)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
`

**Comment by mp911de** [comment]
Spring Data JPA requires Hibernate 6.1.
