### ISSUE TITLE
ClassCastException when using @ElementCollection with enums

### ISSUE THREAD

**Issue by otto-vodvarka** [spring-projects/spring-data-jpa#2743]
Hi, 

after upgrading to Spring Boot 3.0 I'm receiving the following error when requesting an entity (User) with collection of enums (Role):

```
java.lang.ClassCastException: class java.util.LinkedHashSet cannot be cast to class java.lang.Enum (java.util.LinkedHashSet and java.lang.Enum are in module java.base of loader 'bootstrap')
	at org.hibernate.type.EnumType.disassemble(EnumType.java:72) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.type.CustomType.disassemble(CustomType.java:205) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.metamodel.mapping.Bindable.forEachJdbcValue(Bindable.java:149) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:92) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.sql.exec.spi.JdbcParameterBindings.registerParametersForEachJdbcValue(JdbcParameterBindings.java:82) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.SqmUtil.createValueBindings(SqmUtil.java:394) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.SqmUtil.createJdbcParameterBindings(SqmUtil.java:326) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:393) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:300) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:276) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:571) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:1073) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.hibernate.query.Query.getResultList(Query.java:94) ~[hibernate-core-6.1.6.Final.jar:6.1.6.Final]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$PagedExecution.doExecute(JpaQueryExecution.java:174) ~[spring-data-jpa-3.0.0.jar:3.0.0]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90) ~[spring-data-jpa-3.0.0.jar:3.0.0]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148) ~[spring-data-jpa-3.0.0.jar:3.0.0]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136) ~[spring-data-jpa-3.0.0.jar:3.0.0]
```

User class:
```
    @Basic
    @Column(name = "username")
    private String username;

    @Basic
    @Column(name = "first_name")
    private String firstName;

    @Basic
    @Column(name = "last_name")
    private String lastName;

    @Basic
    @Column(name = "email")
    private String email;

    @ElementCollection(targetClass = Role.class, fetch = FetchType.EAGER)
    @CollectionTable(name = "user_role", joinColumns = @JoinColumn(name = "user_id"))
    @Column(name = "role", nullable = false)
    @Enumerated(EnumType.STRING)
    private Collection<Role> roles;
```

Role enum: 

`ADMIN, CUSTOMER;`

**Comment by schauder** [comment]
I failed to reproduce the issue in https://github.com/schauder/issue-JPA-2743-enums.

Please provide a [Minimimal Reproducable Example](https://stackoverflow.com/help/minimal-reproducible-example), preferable as a Github repository. Make sure to include the database, either as an in memory database or if that is not possible using [Testcontainers](https://www.testcontainers.org/).

**Comment by otto-vodvarka** [comment]
I've looked a little bit more into it and I found out that this custom database query is responsible for the problem:
`
@Query("SELECT DISTINCT u FROM User AS u JOIN u.roles role WHERE role IN :visibleRolesSet AND ( :filterRolesSet is null OR role in :filterRolesSet)")
Page<User> test(@Param("visibleRolesSet") Set<Role> visibleRoles, @Param("filterRolesSet") Set<Role> filterByRole, Pageable pageable);
`

It doesn't matter what roles I use for the query. Interesting thing is that It does not happen every time I start up the application. It probably depends on something in the application startup because it occures either every time or not at all.

Could you please try it with this query?

**Comment by schauder** [comment]
> Could you please try it with this query?

Please provide a full reproducer. A PR for the repository I created would be perfect.

**Comment by otto-vodvarka** [comment]
@schauder I've managed to reproduce the issue in the provided repository. See the created PR.

**Comment by schauder** [comment]
Thanks for the PR. I modified the reproducer further to recreate the issue based on the JPA API alone. This suggests, that the issue is in Hibernate, although I guess we would need a reproducer without Spring to convince the Hibernate team.

As you described in your PR the issue occurs only some of the time. If it does occur it happens for both the Spring Data and the JPA variant, suggesting a race condition during creation of the `EntityManager`.

The issue seems to disappear when the `IS NULL` part of the query is removed. At least I couldn't reproduce it with about 10 runs of the tests.

I'll try to recreate a pure Hibernate reproducer.

**Comment by schauder** [comment]
I was able to reproduce the behaviour with Hibernate alone and created a ticket with them: https://hibernate.atlassian.net/browse/HHH-15968
