### ISSUE TITLE
Build fails in ParentRepositoryIntegrationTests and RoleRepositoryIntegrationTests

### ISSUE THREAD

**Issue by krzyk** [spring-projects/spring-data-jpa#2745]
I did a fresh checkout of the main branch and tried `mvn clean install` and it failed with:
```
[ERROR] Errors:
[ERROR]   ParentRepositoryIntegrationTests.setUp:58 » BeanCreation Error creating bean w...
[ERROR]   ParentRepositoryIntegrationTests.setUp:58 » BeanCreation Error creating bean w...
[ERROR]   RoleRepositoryIntegrationTests.createsRole:51 » BeanCreation Error creating be...
[ERROR]   RoleRepositoryIntegrationTests.shouldUseExplicitlyConfiguredEntityNameInDerivedCountQueries:91 » BeanCreation
[ERROR]   RoleRepositoryIntegrationTests.shouldUseExplicitlyConfiguredEntityNameInOrmXmlInCountQueries:73 » BeanCreation
[ERROR]   RoleRepositoryIntegrationTests.shouldUseExplicitlyConfiguredEntityNameInOrmXmlInExistsQueries:82 » BeanCreation
[ERROR]   RoleRepositoryIntegrationTests.updatesRole:59 » BeanCreation Error creating be...
```

One of stacktraces:
```
[ERROR] org.springframework.data.jpa.repository.ParentRepositoryIntegrationTests.testWithJoin  Time elapsed: 0.003 s  <<< ERROR!
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.data.auditing.AuditingHandler#0': Cannot create inner bean '(inner bean)#461c9e86' of type [org.springframework.data.repository.config.PersistentEntitiesFactoryBean] while setting constructor argument
        at org.springframework.data.jpa.repository.ParentRepositoryIntegrationTests.setUp(ParentRepositoryIntegrationTests.java:58)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#461c9e86': Cannot resolve reference to bean 'jpaMappingContext' while setting constructor argument
        at org.springframework.data.jpa.repository.ParentRepositoryIntegrationTests.setUp(ParentRepositoryIntegrationTests.java:58)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jpaMappingContext': org.springframework.context.support.GenericApplicationContext@7a66b886 has been closed already
        at org.springframework.data.jpa.repository.ParentRepositoryIntegrationTests.setUp(ParentRepositoryIntegrationTests.java:58)
Caused by: java.lang.IllegalStateException: org.springframework.context.support.GenericApplicationContext@7a66b886 has been closed already
        at org.springframework.data.jpa.repository.ParentRepositoryIntegrationTests.setUp(ParentRepositoryIntegrationTests.java:58)
```

I couldn't find any information in CONTRIBUTING or in README that I should setup my environment in specific way to allow those tests to pass.

**Comment by schauder** [comment]
This typically happens when you don't have a current/matching version of Spring Data Commons.

To fix it, check out Spring Data Commons and `./mvnw clean install` it.

If that doesn't help, please checkout a released version using a tag, like https://github.com/spring-projects/spring-data-jpa/releases/tag/3.0.0 and try to build that. That should work, since dependencies are stable and published to Maven Central. This should clarify if something deeper is broken that needs fixing first.

**Comment by krzyk** [comment]
OK, so I did that, but I got identical build error.

So that got me thinking and tests work fine when I run them in IDE. So I changed the `runOrder` (to `random`) in surefire for integration tests and build passed.

Looks like there is some dependency between the integration tests, one of the tests breaks something that makes those two test classes work incorrectly (they run last in my system).

**Comment by schauder** [comment]
Could you provide a logfile or similar from which we can see in what order the tests got executed to reproduce the failure?

**Comment by krzyk** [comment]
Sure here it is 
[build.log](https://github.com/spring-projects/spring-data-jpa/files/10335124/build.log)

I'm also able to reproduce it when running mvn inside the spring-data-jpa module (it is a bit of a problem, because that list is used in all the execution contexts, so unit-test, integration-test, eclipselink-test, etc. - and might sometimes fail in the vendor specific tests which is expected because only portion of those tests should be executed there):
```
 mvn clean install -Dtest=AuditingEntityListenerTests,QueryByExampleWithOptionalEmptyTests,AuditingEntityWithEmbeddableListenerTests,JpaSortTests,PersistenceProviderIntegrationTests,JpaMetamodelCacheCleanupIntegrationTests,HibernateMetamodelIntegrationTests,Jsr310JpaConvertersIntegrationTests,JpaMetamodelMappingContextIntegrationTests,NamespaceUserRepositoryTests,AbstractPersistableIntegrationTests,QuerydslJpaRepositoryTests,QuerydslRepositorySupportIntegrationTests,TransactionalRepositoryTests,EntityManagerBeanDefinitionRegistrarPostProcessorIntegrationTests,QuerydslIntegrationTests,JavaConfigDefaultTransactionDisablingIntegrationTests,MailMessageRepositoryIntegrationTests,DefaultJpaContextIntegrationTests,JpaRepositoryFactoryBeanEntityPathResolverIntegrationTests,HibernateJpaMetamodelEntityInformationIntegrationTests,QuerydslRepositorySupportTests,EntityManagerFactoryRefTests,JpaRepositoryTests,XmlConfigDefaultTransactionDisablingIntegrationTests,SimpleJpaParameterBindingTests,QueryByExampleHibernateIntegrationTests,UserRepositoryTests,RepositoryWithCompositeKeyTests,MappedTypeRepositoryIntegrationTests,EntityGraphRepositoryMethodsIntegrationTests,RepositoryWithIdClassKeyTests,UserRepositoryFinderTests,ProjectionsIntegrationTests,ProjectionJoinIntegrationTests,EntityWithAssignedIdIntegrationTests,ORMInfrastructureTests,JavaConfigUserRepositoryTests,StoredProcedureIntegrationTests,UserRepositoryStoredProcedureIntegrationTests,RedeclaringRepositoryMethodsTests,SPR8954Tests,CustomAbstractPersistableIntegrationTests,QueryByExampleEclipseLinkIntegrationTests,AllowNestedRepositoriesRepositoryConfigTests,ExplicitAuditingViaJavaConfigRepositoriesTests,JpaRepositoriesRegistrarIntegrationTests,AuditingBeanDefinitionParserTests,RepositoryAutoConfigTests,RepositoryConfigTests,DefaultAuditingViaJavaConfigRepositoriesTests,TypeFilterConfigTests,RepositoriesJavaConfigTests,NestedRepositoriesJavaConfigTests,CustomRepositoryFactoryConfigTests,QueryLookupStrategyTests,JpaRepositoryConfigDefinitionParserTests,QueryUtilsIntegrationTests,AbstractStringBasedJpaQueryIntegrationTests,MetaAnnotatedQueryMethodEclipseLinkIntegrationTests,QueryWithNullLikeHibernateIntegrationTests,CustomNonBindableJpaParametersIntegrationTests,AbstractJpaQueryTests,Jpa21UtilsTests,ParameterMetadataProviderIntegrationTests,JpaQueryRewriteIntegrationTests,PartTreeJpaQueryIntegrationTests,JpaParametersParameterAccessorTests,MetaAnnotatedQueryMethodHibernateIntegrationTests,ParameterExpressionProviderTests,JpaCountQueryCreatorIntegrationTests,CdiExtensionIntegrationTests,JpaQueryRewriterWithCdiIntegrationTests,RoleRepositoryIntegrationTests,ParentRepositoryIntegrationTests
 ```
 
 Playing around with that list will result sometimes in different errors, so there is some stale data kepts somehow. A simple solution would be to make surefire use forkCount=1 and reuseForks=false, but that would also make the tests run slower.
 
I also able to bisect the issue to this commit: 3d8b287e0e2129ec827b15613b44f31c19c65c61

When I disable the test `QueryWithNullLikeHibernateIntegrationTests` which was added there my build passes.

I'm still looking at it, maybe I'll be able to find the root cause.

**Comment by schauder** [comment]
Thanks, that's great work. If you find the root cause a PR would be highly appreciated.

**Comment by krzyk** [comment]
I got a simple solution (more like a workaround), adding `@DirtiesContext` to `QueryWithNullLikeHibernateIntegrationTests` solves the issue. I wasn't able to find the root cause unfortunatelly, so clearing the context makes it work.

Are you OK with such change?

**Comment by gregturn** [comment]
I went into `/tmp`, did a fresh git clone, and was able to to `./mvnw clean install` with no problem.

Could you please share the platform you are working on (`uname -a` output if possible), the version of JDK you are using (`java --version` and `javac --version` if possible), the exact command you issued, and a complete output of the build system?

**Comment by krzyk** [comment]
@gregturn I provided the command above in https://github.com/spring-projects/spring-data-jpa/issues/2745#issuecomment-1370657575.

uname is:
```
Linux krzyk 6.0.9 #1 SMP PREEMPT Wed Nov 16 13:48:21 CET 2022 x86_64 x86_64 x86_64 GNU/Linux
```

java --version:
```
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-39)
OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)
```

javac --version:
```
javac 17.0.1
```

Full build log (for `./mvnw clean install | tee build.log` - I used a zipped current main branch that I downloaded from https://codeload.github.com/spring-projects/spring-data-jpa/zip/refs/heads/main into `/tmp`: 

The default runOrder in surefire is dependent on the filesystem, AFAIR it depends in what order the files were created during checkout.
I would propose to change it to e.g. `random` so you would find clashes between tests sooner (but in a well, random way).

**Comment by gregturn** [comment]
@krzyk Do you keep experiencing the same failures? Because @odrotbohm pushed through a commit a couple months ago that may have altered things (https://github.com/spring-projects/spring-data-jpa/commit/9293c911e9d48b79fbc7ac235513be02b5738bc4).

Give it a go, and tell us if the issue persists.
