### ISSUE TITLE
Named native queries do not work with JPA repositories

### ISSUE THREAD

**Issue by isaul32** [spring-projects/spring-data-jpa#2779]
Named native queries do not work with Spring Data 3.0.1 JPA repositories. Spring Data JPA calls the entity manager with jakarta.persistence.Tuple resultClass. It will throw a NullPointerException:
```
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "aliases[i]" is null
```
Used versions:
```
Spring Boot: 3.0.2
Spring Data JPA: 3.0.1

JDK: Eclipse Temurin 17 LTS
OS: macOS 13 & Manjaro
```

Example: https://github.com/isaul32/spring-data-jpa-named-native-query-bug

**Comment by mp911de** [comment]
With the same stack trace showing up using Hibernate directly and through Spring Data, how do you consider this being a Spring Data bug?

```
Cannot invoke "String.toLowerCase()" because "aliases[i]" is null
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "aliases[i]" is null
	at org.hibernate.jpa.spi.NativeQueryTupleTransformer$NativeTupleImpl.<init>(NativeQueryTupleTransformer.java:79)
	at org.hibernate.jpa.spi.NativeQueryTupleTransformer.transformTuple(NativeQueryTupleTransformer.java:29)
	at org.hibernate.jpa.spi.NativeQueryTupleTransformer.transformTuple(NativeQueryTupleTransformer.java:25)
	at org.hibernate.sql.results.internal.RowTransformerTupleTransformerAdapter.transformRow(RowTransformerTupleTransformerAdapter.java:30)
	at org.hibernate.sql.results.internal.StandardRowReader.readRow(StandardRowReader.java:109)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:198)
	at org.hibernate.sql.results.spi.ListResultsConsumer.consume(ListResultsConsumer.java:33)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:443)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:166)
	at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:91)
	at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
	at org.hibernate.query.sql.internal.NativeSelectQueryPlanImpl.performList(NativeSelectQueryPlanImpl.java:105)
	at org.hibernate.query.sql.internal.NativeQueryImpl.doList(NativeQueryImpl.java:602)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)
	at org.hibernate.query.Query.getResultList(Query.java:94)
	at com.example.demo.DemoApplicationTests.testNamedNativeQueries3(DemoApplicationTests.java:57)
```

**Comment by isaul32** [comment]
I apologise that the test cases are presented in a bit unclear way. `testNamedNativeQueries3` is there to show what happens inside Spring Data. `testNamedNativeQueries4` is the actual bug test case.

Somehow the value of `typeToRead` is jakarta.persistence.Tuple and not DemoPojo.class as it should be in
https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/NamedQuery.java#L170-L172

I think it gets jakarta.persistence.Tuple from https://github.com/spring-projects/spring-data-jpa/blob/main/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/AbstractJpaQuery.java#L278.

**Comment by mp911de** [comment]
Thanks a lot for the clarification. Did that arrangement work for you with Spring Data JPA 2.7? The query is defined with a DTO projection so we construct a tuple query. That is, why we want to read `jakarta.persistence.Tuple` and not `DemoPojo`.

DTO projections are only supported through constructor expressions (`SELECT new DemoPojo(…) FROM …`).

**Comment by mp911de** [comment]
Thanks a lot. Feel free to file a bug report in the [Hibernate issue tracker](https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/?filter=allissues) and leave a link to the ticket in the comments here.

**Comment by isaul32** [comment]
Thank you for your help and quick replies.

Now there is a bug report in the Hibernate issue tracker: https://hibernate.atlassian.net/browse/HHH-16119.

**Comment by isaul32** [comment]
@mp911de I think this issue should maybe reopened.

The Hibernate team fixed NPE (https://github.com/hibernate/hibernate-orm/pull/6096).

https://github.com/isaul32/spring-data-jpa-named-native-query-bug/pull/3 with the new version (Hibernate ORM 6.2.0.CR3) testNamedNativeQueries4 throws:
```
No converter found capable of converting from type [org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap] to type [com.example.demo.DemoPojo]
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap] to type [com.example.demo.DemoPojo]
	at app//org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322)
	at app//org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195)
	at app//org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175)
	at app//org.springframework.data.repository.query.ResultProcessor$ProjectingConverter.convert(ResultProcessor.java:300)
	at app//org.springframework.data.repository.query.ResultProcessor$ChainingConverter.lambda$and$0(ResultProcessor.java:228)
	at app//org.springframework.data.repository.query.ResultProcessor$ChainingConverter.convert(ResultProcessor.java:235)
	at app//org.springframework.data.repository.query.ResultProcessor.processResult(ResultProcessor.java:155)
	at app//org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:151)
	at app//org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
	at app//org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at app//org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at app//org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at app//org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at app//org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at app//org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at app//org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at app//org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at app//org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at app//org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at app//org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at app/jdk.proxy3/jdk.proxy3.$Proxy107.findAllCustom(Unknown Source)
	at app//com.example.demo.DemoApplicationTests.testNamedNativeQueries4(DemoApplicationTests.java:66)
```

**Comment by schauder** [comment]
The bug was classified as a Hibernate Bug and everything seems to indicate that this was correct. If there is still something not working, please open a new issue.

Otherwise it gets really hard to read and understand the issues when they kind of morph through the comments.
