### ISSUE TITLE
Unable to build Hibernate SessionFactory; Named type [typeName] did not implement BasicType nor UserType

### ISSUE THREAD

**Issue by asavov** [spring-projects/spring-data-jpa#2783]
**The Problem**

After migration to Spring Boot 3.0.2 and Hibernate 6 I'm hitting this exception:

`LocalContainerEntityManagerFactoryBean : Failed to initialize JPA EntityManagerFactory: [PersistenceUnit: default] Unable to build Hibernate SessionFactory; nested exception is java.lang.IllegalArgumentException: Named type [class com.example.demo.DemoApplication$ServiceTaskCallback] did not implement BasicType nor UserType`

The code change is related to new Hibernate **@Type** system.

The code is changed **from**:

```
        @Type(type = "jsonb")
        @Column(columnDefinition = "jsonb")
        public ServiceTaskCallback serviceTaskCallback;
```
**to** 

```
        @Type(io.hypersistence.utils.hibernate.type.json.JsonBinaryType.class)
        @Column(columnDefinition = "jsonb")
        public ServiceTaskCallback serviceTaskCallback;
```

Similar problem is reported by this [stackoverflow](https://stackoverflow.com/questions/74928307/hibernate-upgrade-to-v6-spring-boot-3-named-type-interface-java-util-list) issue.

Here's the **repro** code (generated through Spring Initialiser):
```
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @MappedSuperclass
    public static class ServiceDocument {
        @Id
        public String documentSelfLink;
    }

    @MappedSuperclass
    public static class MultiTenantDocument extends ServiceDocument {

        @Type(JsonBinaryType.class)
        @Column(columnDefinition = "jsonb")
        public List<String> tenantLinks;

        // NOTE: If this is uncommented and below fragment (which is the SAME) is commented then it works.  
        // @Type(JsonBinaryType.class)
        // @Column(columnDefinition = "jsonb")
        // public ServiceTaskCallback serviceTaskCallback;
    }

    @MappedSuperclass
    public static class TaskServiceDocument<E extends Enum<E>> extends MultiTenantDocument {

        @Type(JsonBinaryType.class)
        @Column(columnDefinition = "jsonb")
        public ServiceTaskCallback serviceTaskCallback;
    }

    public static class ServiceTaskCallback {

        public String serviceSelfLink;
    }

    @Entity
    public static class GenericTaskState extends TaskServiceDocument<GenericTaskState.SubStage> {

        public enum SubStage { CREATED }

        public String taskId;
    }
}
```

Here's **application.properties**:
```
spring.datasource.url= jdbc:postgresql://localhost:5432/test
spring.datasource.username= postgres
spring.datasource.password= password
```

Here's **maven** deps:

```
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>io.hypersistence</groupId>
            <artifactId>hypersistence-utils-hibernate-60</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
    </dependencies>
```

**Observation**: The exception is thrown by `org.hibernate.boot.model.TypeDefinition#createResolution`

**Refs**:
- https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#type-system
- https://docs.jboss.org/hibernate/orm/6.0/userguide/html_single/Hibernate_User_Guide.html#basic-mapping-custom

**Comment by mp911de** [comment]
I can reproduce the issue without Spring entirely hence I do not consider this ticket a Spring bug:

```java
EntityManagerFactory emf = Persistence.createEntityManagerFactory("my-persistence-unit", new HashMap());

EntityManager entityManager = emf.createEntityManager();
entityManager.createQuery("SELECT u FROM ServiceDocument u").getResultList();
```

persistence.xml
```xml
<persistence xmlns="http://java.sun.com/xml/ns/persistence"
			 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://java.sun.com/xml/ns/persistence http://java.sun.com/xml/ns/persistence/persistence_2_0.xsd"
			 version="2.0">
	<persistence-unit name="my-persistence-unit">
		<properties>
			<!-- JPA 3.x -->
			<property name="jakarta.persistence.jdbc.driver" value="org.postgresql.Driver" />
			<property name="jakarta.persistence.jdbc.url" value="jdbc:postgresql://localhost:5432/postgres" />
			<property name="jakarta.persistence.jdbc.user" value="…" />
			<property name="jakarta.persistence.jdbc.password" value="…" />

		</properties>
	</persistence-unit>
</persistence>

```

```
Exception in thread "main" jakarta.persistence.PersistenceException: [PersistenceUnit: my-persistence-unit] Unable to build Hibernate SessionFactory
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1509)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1430)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:55)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at com.example.reprojpa.ReproJpaApplication.main(ReproJpaApplication.java:26)
Caused by: java.lang.IllegalArgumentException: Named type [class com.example.reprojpa.ReproJpaApplication$ServiceTaskCallback] did not implement BasicType nor UserType
	at org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:271)
	at org.hibernate.boot.model.TypeDefinition.createResolution(TypeDefinition.java:121)
	at org.hibernate.boot.model.TypeDefinition.resolve(TypeDefinition.java:106)
	at org.hibernate.mapping.BasicValue.interpretExplicitlyNamedType(BasicValue.java:671)
	at org.hibernate.mapping.BasicValue.buildResolution(BasicValue.java:353)
	at org.hibernate.mapping.BasicValue.resolve(BasicValue.java:315)
	at org.hibernate.mapping.BasicValue.getType(BasicValue.java:293)
	at org.hibernate.metamodel.internal.AttributeFactory.determineAttributeMetadata(AttributeFactory.java:375)
	at org.hibernate.metamodel.internal.AttributeFactory.buildAttribute(AttributeFactory.java:111)
	at org.hibernate.metamodel.internal.AttributeFactory.buildAttribute(AttributeFactory.java:96)
	at org.hibernate.metamodel.internal.MetadataContext.wrapUp(MetadataContext.java:331)
	at org.hibernate.metamodel.model.domain.internal.JpaMetamodelImpl.processJpa(JpaMetamodelImpl.java:504)
	at org.hibernate.metamodel.model.domain.internal.MappingMetamodelImpl.finishInitialization(MappingMetamodelImpl.java:244)
	at org.hibernate.metamodel.internal.RuntimeMetamodelsImpl.finishInitialization(RuntimeMetamodelsImpl.java:60)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:311)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:415)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1425)
	... 3 more
```

I recommend reaching out to hypersistence as the JSONB type mapping via `@Type(JsonBinaryType.class)` seems not to work.

**Comment by schauder** [comment]
I discussed this with @asavov. He will create a Hibernate issue and reference it here.
