### ISSUE TITLE
Adopt to changed Hibernate behavior returning domain types using tuple queries

### ISSUE THREAD

**Issue by markusheiden** [spring-projects/spring-data-jpa#2815]
Interface-based projections fail: When calling getId() on the objects returned by the query method, null is returned (-> exception below) though in the database there is an ID set. When using the JPA entity as the return type of the repository method, it works.

The code worked with Spring Boot 2.6 and fails since 2.7+.

```java
public interface IdOnly { long getId(); }

@SequenceGenerator(name = "seq_local_account", sequenceName = "seq_local_account", allocationSize = 1)
@Entity
@Table(name = "local_account")
public class LocalAccount {
    @Id
    @Column(name = "id", nullable = false)
    @GeneratedValue(strategy = SEQUENCE, generator = "seq_local_account")
    private long id;

    @ElementCollection
    @Fetch(SUBSELECT)
    @CollectionTable(name = "local_account_downloaded", joinColumns = @JoinColumn(name = "account_id", nullable = false))
    @Column(name = "month", nullable = false)
    private Set<YearMonth> downloaded = new HashSet<>();

    public long getId() {
        return id;
    }
}

public interface LocalAccountRepository extends Repository<LocalAccount, Long> {
    @Query("FROM LocalAccount WHERE :month NOT MEMBER OF downloaded")
    // Using List<LocalAccount> as return type here make it work.
    List<IdOnly> findAllByNotInDownloaded(YearMonth month);
}

@Converter(autoApply = true)
public class YearMonthConverter implements AttributeConverter<YearMonth, Integer> {
    @Override
    public Integer convertToDatabaseColumn(YearMonth entity) {
        return entity.getYear() * 100 + entity.getMonth().getValue();
    }
   @Override
    public YearMonth convertToEntityAttribute(Integer database) {
        return YearMonth.of(database / 100, database % 100);
    }
}
```

Stacktrace:
```
Caused by: org.springframework.aop.AopInvocationException: Null return value from advice does not match primitive return type for: public abstract long com.adsoul.voluminator.crawler.local.IdOnly.getId()
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:232)
	at jdk.proxy4/jdk.proxy4.$Proxy166.getId(Unknown Source)
        ...
```

**Comment by markusheiden** [comment]
When using `Long`s instead the returned IDs are always `null` (though they are set in the database) and thus lead to failures in the subsequent code which expect the IDs to be present.
