### ISSUE TITLE
Nullpointer Exception when using native query

### ISSUE THREAD

**Issue by schnandr** [spring-projects/spring-data-jpa#2819]
Following repository worked in 3.0.1.

```
public interface SomeRepository extends JpaRepository<Request, Integer> {

  @Query(value = "SELECT usf_request_number();", nativeQuery = true)
  int usfRequestNumber();

}
```

With 3.0.2 (spring boot 3.0.3) I am getting a Nullpointer in QueryUtils.createCountQueryFor that variable is null. 

`Cannot invoke "String.contains(java.lang.CharSequence)" because "variable" is null` 

Maybe related to this fix: https://github.com/spring-projects/spring-data-jpa/issues/2773

**Comment by gideruette** [comment]
I think this is duplicate of #2818

**Comment by uthark** [comment]
I see the same issue after upgrading to spring boot 2.7.9

```
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "variable" is null
        at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607)
        at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49)
        at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:119)
        at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.<init>(AbstractStringBasedJpaQuery.java:72)
        at org.springframework.data.jpa.repository.query.NativeJpaQuery.<init>(NativeJpaQuery.java:53)
        at org.springframework.data.jpa.repository.query.JpaQueryFactory.fromMethodWithQueryString(JpaQueryFactory.java:51)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$DeclaredQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:169)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:253)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:93)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:103)
        ... 122 common frames omitted
```

**Comment by aldingithub** [comment]
Same issue after upgrading to spring boot 3.0.3
```
Caused by: java.lang.NullPointerException: Cannot invoke "String.contains(java.lang.CharSequence)" because "variable" is null
        at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607)
        at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49)
        at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:119)
        at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.<init>(AbstractStringBasedJpaQuery.java:72)
        at org.springframework.data.jpa.repository.query.NativeJpaQuery.<init>(NativeJpaQuery.java:53)
        at org.springframework.data.jpa.repository.query.JpaQueryFactory.fromMethodWithQueryString(JpaQueryFactory.java:51)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$DeclaredQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:169)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:253)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:93)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:103)
        ... 122 common frames omitted
        ```

**Comment by schnandr** [comment]
Duplicates https://github.com/spring-projects/spring-data-jpa/issues/2812
