### ISSUE TITLE
query for Embedded on NoRepositoryBean causes AssertionError in hibernate

### ISSUE THREAD

**Issue by noffke** [spring-projects/spring-data-jpa#2833]
Runnable example for issue: https://github.com/noffke/spring-data-jpa-embedded-test

The issue is present in v3.0.3 but not in the 2.x line (you can change the spring boot dep in the test project to 2.7.9, adapt jakarta to javax, and the test runs fine).

For the following code
```
@Embeddable
data class AnEmbeddable(@Column(nullable = false) val foo: String, @Column(nullable = false) val bar: String)

interface HasEmbeddable{
    val e: AnEmbeddable
}

@Entity
class WithEmbedded(@Id val id: Long, @Embedded override val e: AnEmbeddable): HasEmbeddable

@NoRepositoryBean
interface HasEmbeddableRepository<T: HasEmbeddable, ID, in AnEmbeddable> : JpaRepository<T, ID>{
    fun findByE(e: AnEmbeddable): List<WithEmbedded>
}

interface WithEmbeddedRepository: HasEmbeddableRepository<WithEmbedded, Long, AnEmbeddable>
```

running the `findByE` query will make hibernate throw an `AssertionError`
```
java.lang.AssertionError
	at org.hibernate.query.sqm.internal.SqmUtil.createValueBindings(SqmUtil.java:401)
	at org.hibernate.query.sqm.internal.SqmUtil.createJdbcParameterBindings(SqmUtil.java:326)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:393)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:300)
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:276)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:571)
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:1073)
	at org.hibernate.query.Query.getResultList(Query.java:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:405)
	at jdk.proxy2/jdk.proxy2.$Proxy114.getResultList(Unknown Source)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$CollectionExecution.doExecute(JpaQueryExecution.java:127)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:90)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:148)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:390)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:134)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.MethodInvocationValidator.invoke(MethodInvocationValidator.java:94)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:218)
	at jdk.proxy2/jdk.proxy2.$Proxy92.findByE(Unknown Source)
	at com.example.embeddedtest.EmbeddedTestApplicationTests.contextLoads(EmbeddedTestApplicationTests.kt:30)
```

If I move `findByE` into `WithEmbeddedRepository` and then extend only `JpaRepository` the code runs fine. It looks like somehow the type information for `findByE`'s `e` param is lost.

**Comment by schauder** [comment]
This sounds very much like a Hibernate issue, since all the JPA mapping is done by it and Spring Data JPA doesn't have any special handling for embeddeds.
I recommend creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behaviour using the `EntityManager` directly.

**Comment by noffke** [comment]
@schauder thanks for the hint, after some digging around I can indeed reproduce the issue with a plain jpa criteria query. For reference:

```
        val query = cb.createQuery(WithEmbedded::class.java)
        val root = query.from(WithEmbedded::class.java)
        val parameter = cb.parameter(Any::class.java)
        query.select(root).where(cb.equal(root.get<Any>("e"), parameter))

        val typedQuery = em.createQuery(query)
        typedQuery.setParameter(parameter, AnEmbeddable("a", "b"))
        assertThatCode { typedQuery.resultList }.doesNotThrowAnyException()
```

**Comment by noffke** [comment]
Hibernate issue: https://hibernate.atlassian.net/browse/HHH-16247
