### ISSUE TITLE
ClassCastException in PersistenceProvider$HibernateScrollableResultsIterator.next with GraalVM native-image

### ISSUE THREAD

**Issue by derkoe** [spring-projects/spring-data-jpa#2848]
When you create a repository method that returns a `Stream<Entity>` and you compile and run the application with GraalVM native-image the following error occurs:

```
java.lang.ClassCastException: Entity cannot be cast to java.lang.Object[]
org.springframework.data.jpa.provider.PersistenceProvider$HibernateScrollableResultsIterator.next(PersistenceProvider.java:394)
```
---

How to reproduce:
1. Clone https://github.com/derkoe/spring-data-jpa-native
2.  mvnw -PnativeTest test     
3. You see the error in the test log

You can also build the app with native-image, run it and open http://localhost:8080/test

---

Here is the full stack trace of the error when calling http://localhost:8080/test
``` 
java.lang.ClassCastException: com.example.jpanative.TestEntity cannot be cast to java.lang.Object[]
        at org.springframework.data.jpa.provider.PersistenceProvider$HibernateScrollableResultsIterator.next(PersistenceProvider.java:394) ~[na:na]
        at java.base@17.0.6/java.util.Iterator.forEachRemaining(Iterator.java:133) ~[jpa-native:na]
        at java.base@17.0.6/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622) ~[jpa-native:na]
        at java.base@17.0.6/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627) ~[jpa-native:na]
        at com.example.jpanative.TestController.names(TestController.java:21) ~[jpa-native:na]
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568) ~[jpa-native:na]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343) ~[na:na]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196) ~[jpa-native:6.0.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[jpa-native:6.0.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[na:na]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[na:na]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:390) ~[jpa-native:6.0.6]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[jpa-native:6.0.6]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[jpa-native:6.0.6]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[na:na]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702) ~[na:na]
        at com.example.jpanative.TestController$$SpringCGLIB$$0.names(<generated>) ~[jpa-native:na]
        at java.base@17.0.6/java.lang.reflect.Method.invoke(Method.java:568) ~[jpa-native:na]
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[jpa-native:6.0.6]
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[jpa-native:6.0.6]
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[jpa-native:6.0.6]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[jpa-native:6.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[jpa-native:6.0.6]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[jpa-native:6.0]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:223) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[jpa-native:10.1.5]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[jpa-native:6.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[jpa-native:6.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[jpa-native:6.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[jpa-native:6.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[jpa-native:6.0.6]
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[jpa-native:6.0.6]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:185) ~[na:na]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:158) ~[na:na]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:177) ~[na:na]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) ~[na:na]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) ~[jpa-native:10.1.5]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:119) ~[na:na]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[jpa-native:10.1.5]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) ~[na:na]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) ~[na:na]
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:400) ~[na:na]
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[jpa-native:10.1.5]
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:859) ~[na:na]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1734) ~[na:na]
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[jpa-native:10.1.5]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[na:na]
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[na:na]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[na:na]
        at java.base@17.0.6/java.lang.Thread.run(Thread.java:833) ~[jpa-native:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775) ~[jpa-native:na]
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203) ~[na:na]
```

---

Environment

```
mvn -v
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: ~/.local/share/rtx/installs/maven/3.8.7
Java version: 17.0.6, vendor: GraalVM Community, runtime: ~/.local/share/rtx/installs/java/graalvm-22.3.1+java17
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.90.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"
```

**Comment by christophstrobl** [comment]
@derkoe thanks for reporting and the reproducer. We'll look into it.

**Comment by christophstrobl** [comment]
We're missing a reflection hint to look up the `getResultAsStream` method on `jakarta.persistence.Query`.
I'll update the hints on our side and add a smoke test for it.
@derkoe till the fix is out you may want to provide the hint via `@ImportRuntimeHints` as outlined below.

```java
@SpringBootApplication
@ImportRuntimeHints(MyJpaRuntimeHints.class)
public class JpaNativeApplication { ...

// ...

public class MyJpaRuntimeHints implements RuntimeHintsRegistrar {
    @Override
    public void registerHints(RuntimeHints hints, ClassLoader classLoader) {
        hints.reflection().registerType(Query.class, MemberCategory.INVOKE_PUBLIC_METHODS);
    }
```

**Comment by gregturn** [comment]
Merged to `main`. Backported to `3.0.x`.
