### ISSUE TITLE
createCountQueryFor NPE on nativeQuery

### ISSUE THREAD

**Issue by prowave** [spring-projects/spring-data-jpa#2858]
I recently upgraded Spring Boot from 2.7.5 to 2.7.9 and my application will not start due to the following NPE trying to create count Queries on some of my native queries.

```
Caused by: java.lang.NullPointerException
        at org.springframework.data.jpa.repository.query.QueryUtils.createCountQueryFor(QueryUtils.java:607)
        at org.springframework.data.jpa.repository.query.DefaultQueryEnhancer.createCountQueryFor(DefaultQueryEnhancer.java:49)
        at org.springframework.data.jpa.repository.query.StringQuery.deriveCountQuery(StringQuery.java:119)
        at org.springframework.data.jpa.repository.query.AbstractStringBasedJpaQuery.<init>(AbstractStringBasedJpaQuery.java:72)
        at org.springframework.data.jpa.repository.query.NativeJpaQuery.<init>(NativeJpaQuery.java:53)
        at org.springframework.data.jpa.repository.query.JpaQueryFactory.fromMethodWithQueryString(JpaQueryFactory.java:51)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$DeclaredQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:169)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$CreateIfNotFoundQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:253)
        at org.springframework.data.jpa.repository.query.JpaQueryLookupStrategy$AbstractQueryLookupStrategy.resolveQuery(JpaQueryLookupStrategy.java:93)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lookupQuery(QueryExecutorMethodInterceptor.java:103)
        ... 277 more
```

Here is the debugger showing that `variable` is null when parsing the query:

```
  @Query(value = "with x as (select distinct z.city_name, z.state_abbr, z.state_name, (select min(zip_code_gk) "
      + " from zip_code where city_name = z.city_name and state_abbr = z.state_abbr) as zip_code_gk "
      + " from zip_code z "
      + " where z.county_name = upper(:queryString) AND (upper(z.state_name) = upper(:queryString2) "
      + " OR upper(z.state_abbr) = upper(:queryString2)))" + " select zc.* from zip_code zc, x "
      + " where zc.zip_code_gk = x.zip_code_gk order by upper(zc.city_name) asc, "
      + " upper(zc.state_name) asc", nativeQuery = true)
  List<ZipCode> queryCountyState(@Param("queryString") String queryString, @Param("queryString2") String queryString2);
```

![createCountQueryFor-NPE](https://user-images.githubusercontent.com/4467101/225090647-27c1215b-cf02-4766-a69a-8a78965b0c90.jpg)

This also happens when natively calling stored procedures like this:

```
  @Modifying
  @Query(value = "call createCompany.copyCompanyTemplate(?1)", nativeQuery = true)
  void copyCompanyTemplate(Long companyGk);

  @Modifying
  @Query(value = "call createCompany.createCompanyFromTemplate(?1, ?2, ?3)", nativeQuery = true)
  void createCompanyFromTemplate(Long companyGk, String companyName, Long userGk);
```

**Comment by prowave** [comment]
In Spring Boot 2.7.8 all is good.  HTH :)

**Comment by prowave** [comment]
Thank you.
