### ISSUE TITLE
No Such Method Error: isScrollQuery

### ISSUE THREAD

**Issue by jpeschke2608** [spring-projects/spring-data-jpa#2953]
Hello,
After upgrading to Spring Data JPA 3.0.1, I get an exception when trying to intialize my JPA repositories, because the method "isScrollQuery" is missing.
(My application stack is Spring Boot 3.0.6 )

Did I forget to migrate / upgrade something?

```
Caused by: java.lang.NoSuchMethodError: 'boolean org.springframework.data.jpa.repository.query.JpaQueryMethod.isScrollQuery()'

	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.lambda$new$0(QueryExecutorMethodInterceptor.java:88)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.<init>(QueryExecutorMethodInterceptor.java:88)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport.getRepository(RepositoryFactorySupport.java:357)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.lambda$afterPropertiesSet$5(RepositoryFactoryBeanSupport.java:279)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
	at org.springframework.data.repository.core.support.RepositoryFactoryBeanSupport.afterPropertiesSet(RepositoryFactoryBeanSupport.java:285)
	at org.springframework.data.jpa.repository.support.JpaRepositoryFactoryBean.afterPropertiesSet(JpaRepositoryFactoryBean.java:132)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 44 common frames omitted

```

**Comment by christophstrobl** [comment]
this sounds like a dependency issue. Did you upgrade to`data-jpa:3.1.0`? In that case please align `spring-data-commons` to the required version or use the [spring-data-bom](https://github.com/spring-projects/spring-data-bom/tags) / boot property.

**Comment by schauder** [comment]
> Did I forget to migrate / upgrade something?
The short and rather unhelpful answer ist "Yes".

The real question is: why are you managing the version of Spring Data JPA explicitly anyway? 
When using Spring Boot you really should only specify the boot version and let all the other versions be derived from that.

Only in special cases should you explicitly set the version of other dependencies. For example when Spring Data JPA published a new bugfix release that you need and want.

**Comment by jpeschke2608** [comment]
@schauder @christophstrobl 
I'm terribly sorry, my bad :( - you're both absolutely correct:
I explicitely pinned the version of spring-data-jpa due to Issue https://github.com/spring-projects/spring-boot/issues/34363 and forgot to remove it after the new release. I missed that one when analyzing the exception.

Sorry for bothering.

**Comment by schauder** [comment]
Not a reason to feel sorry. Glad we could resolve the issue.
