### ISSUE TITLE
Add support for Hibernate CTE in HQL parser

### ISSUE THREAD

**Issue by clementdenis** [spring-projects/spring-data-jpa#2981]
Hibernate 6.2 introduced [CTE support](https://in.relation.to/2023/02/20/hibernate-orm-62-ctes/).

But in Spring Data JPA 3.1 (that depends on Hibernate 6.2); such queries are rejected by the HQL parser:

```
org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:0 mismatched input 'with' expecting {'(', DELETE, FROM, INSERT, SELECT, UPDATE}; Bad JPQL grammar [with maxId as(
select max(sr.snapshot.id) snapshotId from SnapshotReference sr
    where sr.id.selectionId = ?1 and sr.enabled
    group by sr.userId
    )
select sr from maxId m join SnapshotReference sr on sr.snapshot.id = m.snapshotId
]
	at org.springframework.data.jpa.repository.query.BadJpqlGrammarErrorListener.syntaxError(BadJpqlGrammarErrorListener.java:39)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at org.springframework.data.jpa.repository.query.HqlParser.ql_statement(HqlParser.java:341)
	at org.springframework.data.jpa.repository.query.HqlParser.start(HqlParser.java:250)
	at org.springframework.data.jpa.repository.query.HqlQueryParser.parseQuery(HqlQueryParser.java:53)
	at org.springframework.data.jpa.repository.query.HqlQueryParser.parse(HqlQueryParser.java:63)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.lambda$new$0(JpaQueryParserSupport.java:182)
	at org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
	at org.springframework.data.util.Lazy.get(Lazy.java:114)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.getContext(JpaQueryParserSupport.java:194)
	at org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:54)
```

My query here works just fine when creating the query directly with the entity manager.

**Comment by clementdenis** [comment]
Until the HQL parser gets updated for Hibernate 6.2, is there a way to disable the query parser for specific queries?

**Comment by gregturn** [comment]
There isn't any way to disable the query parser.

You can either work around this with a custom implementation. Check out https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations for more details on how to hook such a solution into your repository.

However, it won't take long for me to add support.

**Comment by gregturn** [comment]
Merged to `main` and backported to `3.1.x`.

**Comment by Aniket-Singla** [comment]
Hi @gregturn / @clementdenis can you please point me to examples of using CTE with Spring Data JPA + Hibernate. I am getting exception 

``` 	Caused by: org.hibernate.query.sqm.EntityTypeException: Could not resolve entity name 'samCTE' ```

More Details on https://stackoverflow.com/questions/78004995/cte-usage-with-spring-data-jpa-3-2-hibernate-6-4-does-not-work . Hibernate Query checks is expecting to define an Entity for name of CTE .

**Comment by CatPlanet** [comment]
polite bump

**Comment by hosamaly** [comment]
Does the support for CTEs extend to `INSERT ... <query>` statements?
