### ISSUE TITLE
 java.lang.NoSuchMethodException: org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard.<init>() with GraalVM native-image

### ISSUE THREAD

**Issue by ideaviewes** [spring-projects/spring-data-jpa#2986]
When  you compile and run the application with GraalVM native-image the following error occurs:
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': Default-resolver threw exception
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1156) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:931) ~[kt.exe:6.0.9]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[kt.exe:6.0.9]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305) ~[kt.exe:3.1.0]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294) ~[kt.exe:3.1.0]
        at com.icodeview.kt.KtApplicationKt.main(KtApplication.kt:13) ~[kt.exe:na]
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Default-resolver threw exception
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:223) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:180) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl.<init>(MetadataBuilderImpl.java:750) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl.<init>(MetadataBuilderImpl.java:140) ~[na:na]
        at org.hibernate.boot.MetadataSources.getMetadataBuilder(MetadataSources.java:163) ~[na:na]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:269) ~[kt.exe:6.2.2.Final]
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:190) ~[kt.exe:6.2.2.Final]
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60) ~[na:na]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396) ~[kt.exe:6.0.9]
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816) ~[kt.exe:6.0.9]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[kt.exe:6.0.9]
        ... 16 common frames omitted
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Could not instantiate named strategy class [org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:244) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:180) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveDefaultableStrategy(StrategySelectorImpl.java:167) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl$2.call(MetadataBuilderImpl.java:756) ~[na:na]
        at org.hibernate.boot.internal.MetadataBuilderImpl$MetadataBuildingOptionsImpl$2.call(MetadataBuilderImpl.java:753) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:220) ~[na:na]
        ... 29 common frames omitted
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Could not instantiate named strategy class [org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.lambda$static$0(StrategySelectorImpl.java:41) ~[na:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:240) ~[na:na]
        ... 34 common frames omitted
Caused by: java.lang.InstantiationException: org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard
        at java.base@17.0.6/java.lang.Class.newInstance(DynamicHub.java:639) ~[kt.exe:na]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.lambda$static$0(StrategySelectorImpl.java:37) ~[na:na]
        ... 35 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.hibernate.boot.model.relational.ColumnOrderingStrategyStandard.<init>()
        at java.base@17.0.6/java.lang.Class.getConstructor0(DynamicHub.java:3585) ~[kt.exe:na]
        at java.base@17.0.6/java.lang.Class.newInstance(DynamicHub.java:626) ~[kt.exe:na]
        ... 36 common frames omitted
```
How to reproduce:
* git clone https://github.com/ideaviewes/ktlearn.git
* ./gradlew nativeCompile
* ./build/native/nativeCompile/kt.exe

**Comment by mp911de** [comment]
Please file this ticket against https://github.com/oracle/graalvm-reachability-metadata/issues as Spring Data JPA doesn't contain any Hibernate-specific reflection hints.

**Comment by ideaviewes** [comment]
@mp911de I really appreciate your response, and I understand my question may have been a bit vague. I’m hoping to use GraalVM to compile a native image of a Spring Boot project that uses Spring Data JPA, but I’m not sure where to start. Thank you for your help!

**Comment by ceszkraft** [comment]
I got the same error. How did you resolved it?

**Comment by ideaviewes** [comment]
@ceszkraft ，https://github.com/oracle/graalvm-reachability-metadata/issues/302
