### ISSUE TITLE
ConverterNotFoundException exception in hql spring-data-jpa-3.1.0 

### ISSUE THREAD

**Issue by teopapath** [spring-projects/spring-data-jpa#2990]
I have a NamedQuery like:

```
@NamedQuery(
        name = exampleQuery,
        query = "select new Pojo("
                + "au.userId, au.status, r.name, r.code, au.creationDate) "
                + "from Au au "
                + "join Role r on r.code = au.code "
                + "where au.accountId = :accountId "
                + "and au.status <> 'PENDING' ")
```

When query is executed a ConverterNotFoundException is thrown.

If i change the query to 

```
@NamedQuery(
        name = exampleQuery,
        query = "select new Pojo("
                + "au.userId, au.status, r.name, r.code, au.creationDate) "
                + "from Au au "
                + "join Role r on r.code = au.code "
                + "where au.accountId = :accountId "
                + "and au.status not in ('PENDING') ")
```
everything works as expected.
It seems that there is a problem in parsing this part: and au.status <> 'PENDING' 
The same query was executing successfully in spring-boot 3.0.7

Stacktrace:
```
org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [org.springframework.data.jpa.repository.query.AbstractJpaQuery$TupleConverter$TupleBackedMap] to type [Pojo]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:322) ~[spring-core-6.0.9.jar:6.0.9]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:195) ~[spring-core-6.0.9.jar:6.0.9]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:175) ~[spring-core-6.0.9.jar:6.0.9]
	at org.springframework.data.repository.query.ResultProcessor$ProjectingConverter.convert(ResultProcessor.java:305) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.lambda$and$0(ResultProcessor.java:233) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.query.ResultProcessor$ChainingConverter.convert(ResultProcessor.java:240) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.query.ResultProcessor.processResult(ResultProcessor.java:160) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:151) ~[spring-data-jpa-3.1.0.jar:3.1.0]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:136) ~[spring-data-jpa-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:77) ~[spring-data-commons-3.1.0.jar:3.1.0]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184) ~[spring-aop-6.0.9.jar:6.0.9]
2.$Proxy262.exampleQuery(Unknown Source) ~[?:?]
```

**Comment by gregturn** [comment]
Last I checked, DTO via construction in the query requires a FQDN class definition. Does your POJO definition really NOT have a package declaration? If so, I'd recommend testing out if putting it into a package and then putting that into the query resolves the issue.

**Comment by teopapath** [comment]
Yes indeed, i just put pojo in the example for the sake of simplicity. The actual code of course contains a fully qualified name. I can updaye the code snippet but this is not the issue.

**Comment by gregturn** [comment]
Can you post your repository definition along with the domain definition?

**Comment by teopapath** [comment]
Repository:

`@Repository
public interface AuthorityRepository extends JpaRepository<Authority, Long>, AuthorityCustomRepository {

    @Transactional(readOnly = true)
    @Query(name =  "exampleQuery")
    List<AuthorityRoleDTO> query(Long accountId);

}
`

Domain:
`@NamedQuery(
        name = "exampleQuery",
        query = "select new api.authorization.core.domain.dto.AuthorityRoleDTO("
                + "au.userId, au.status, r.name, r.code, au.creationDate) "
                + "from Authority au "
                + "join Role r on r.code = au.code "
                + "where au.accountId = :accountId "
                + "and au.status <> 'PENDING' ")`

**Comment by gregturn** [comment]
I can't see anything obvious in the code listings you have provided.

Is there perhaps some way to build a reproducer, staged on github, ideally using https://start.spring.io, H2 (or Testcontainers for PostGreSQL, etc.), and the version of Spring Boot aligned with your issue?

**Comment by teopapath** [comment]
spring boot version is 3.1.0. I will try to find some time to implement a test project

**Comment by teopapath** [comment]
created a test project that reproduces the error in https://github.com/teopapath/spring-boot-error. Changing the spring-boot version makes the test successful.

**Comment by gregturn** [comment]
Simply switching from:

```
    @Transactional(readOnly = true)
    @Query(name =  Authority.NAMED_QUERY_FIND_NON_PENDING_AUTHORITY_ROLE_LIST)
    List<AuthorityRoleDTO> findNonPendingAuthorityRoleList();
```
to
```
    @Transactional(readOnly = true)
//    @Query(name =  Authority.NAMED_QUERY_FIND_NON_PENDING_AUTHORITY_ROLE_LIST)
    @Query("select new com.example.demo.AuthorityRoleDTO("
            + "au.userId, au.status, r.name, r.code, au.creationDate) "
            + "from Authority au "
            + "join Role r on r.code = au.code "
            + "where au.status <> 'PENDING' ")
    List<AuthorityRoleDTO> findNonPendingAuthorityRoleList();
```
seems to solve the problem and make the test go green. So apparently the issue has to do with named queries vs. directly provided ones.

**Comment by gregturn** [comment]
@teopapath Sorry, I wasn't suggesting that you alter your app. I'm simply tracking that this might be where the discrepancy lies.

**Comment by teopapath** [comment]
@gregturn it seems that the issue still exists in 3.1.2. Test case can be found in [error2990_2](https://github.com/teopapath/spring-boot-error/tree/master/src/main/java/com/example/demo/error2990_2)

**Comment by gregturn** [comment]
Well, the scenario this ticket as closed against was lack of support for `<>` operator, which now operates.

The other scenario where the `NOT IN` isn't working for an `EnumMap`-based relationship sounds like a different scenario, as tracked by #3085.
