### ISSUE TITLE
count sql error,when there is alias (spring-data-jpa 2.5.12)

### ISSUE THREAD

**Issue by scorpiosong** [spring-projects/spring-data-jpa#2992]
Hi,all
I use spring-data-jpa 2.5.12 encountered some error, here is the code

`@query(value = "select * from Merchant m where m.policyMerchantNo= :policyMerchantNo ", nativeQuery = true)
Page findMerchantByqueryKey1(Pageable pageable, @param("policyMerchantNo") String policyMerchantNo);
`

then i execute the code ,i got the sql and the error

`
Hibernate:
select
*
from
Merchant m
where
m.policyMerchantNo= ? limit ?, ?
Hibernate:
select
count(m)
from
Merchant m
where
m.policyMerchantNo= ?
`

org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet

at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551)
at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:242)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:145)

When i remove the alias
`
@query(value = "select * from Merchant where policyMerchantNo= :policyMerchantNo ", nativeQuery = true)
Page findMerchantByqueryKey1(Pageable pageable, @param("policyMerchantNo") String policyMerchantNo);
`
the code works

I check the Commit, and maybe the line 535~540 of src/main/java/org/springframework/data/jpa/repository/query/QueryUtils.java have some bugs.

**Comment by gregturn** [comment]
This situation appears too complicated for `QueryUtils` to handle, and we aren't likely to approve a change there that would meet your needs. Your best best moving forward may be to implement a custom implementation. Check out https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories.custom-implementations for more details on how to hook such a solution into your repository.

**Comment by scorpiosong** [comment]
Thanks。
