### ISSUE TITLE
@Query with class-based projection throws IllegalStateException

### ISSUE THREAD

**Issue by kuntsali** [spring-projects/spring-data-jpa#3001]
Given following setup:

Spring Boot 3.1.0
hypersistence-utils-hibernate-62:3.3.2

SQL:
```
CREATE TYPE status AS ENUM ('DRAFT', 'ACTIVE', 'DISABLED');

CREATE TABLE entity
(
    id                        UUID          NOT NULL,
    name                      VARCHAR(255)  NOT NULL,
    status                    status        NOT NULL
);

```
Enum:
```
public enum Status {
    DRAFT,
    ACTIVE,
    DISABLED
}
```
Entity:
```
@Entity
@Table(name = "entity")
public class Data {

    @Id
    @GeneratedValue
    private UUID id;

    @Column(nullable = false)
    private String name;

    @Column(columnDefinition = "eform_status", nullable = false)
    @Enumerated(EnumType.STRING)
    @Type(PostgreSQLEnumType.class)
    private Status status = Status.DRAFT;
}
```
Repository:
```
public interface DataRepository extends JpaRepository<Data, UUID> {

    @Query("SELECT new com.example.demo.dto.EntityDto(e.id, e.name, e.status) " +
            "FROM Data e WHERE e.id = :id ")
    Optional<EntityDto> find(UUID id);
}
```
DTO:
```
public class EntityDto {

    private final UUID id;
    private final String name;
    private final Status status;

    @java.beans.ConstructorProperties({"id", "name", "status"})
    public EntityDto(UUID id,
                     String name,
                     Status status) {
        this.id = id;
        this.name = name;
        this.status = status;
    }
}
```

If I try to call this repository method, I will get an error:
```
org.springframework.dao.InvalidDataAccessApiUsageException: Could not determine appropriate instantiation strategy - no matching constructor found and one or more arguments did not define alias for bean-injection
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:368) ~[spring-orm-6.0.9.jar:6.0.9]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:234) ~[spring-orm-6.0.9.jar:6.0.9]
....
Caused by: java.lang.IllegalStateException: Could not determine appropriate instantiation strategy - no matching constructor found and one or more arguments did not define alias for bean-injection
	at org.hibernate.sql.results.graph.instantiation.internal.DynamicInstantiationResultImpl.resolveAssembler(DynamicInstantiationResultImpl.java:197) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
	at org.hibernate.sql.results.graph.instantiation.internal.DynamicInstantiationResultImpl.createResultAssembler(DynamicInstantiationResultImpl.java:106) ~[hibernate-core-6.2.2.Final.jar:6.2.2.Final]
```

Enum appears to be a problem here, if I changed it from `Status status` to `Enum<Status> status` in EntityDto constructor, it will work. This issue appears after migration from Spring Boot 2.7.6 to Spring Boot 3. Works fine on Spring Boot 2.7.6

**Comment by gregturn** [comment]
This sounds very much like a Hibernate 6 issue. I'd suggest creating a reproducer based purely on Hibernate and submitting an issue with them.

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behavior using the EntityManager directly.

**Comment by kuntsali** [comment]
Thanks for the response, I will try to reproduce it with pure hibernate
