### ISSUE TITLE
Hibernate duration literals such as "5 MINUTE" no longer pass validation

### ISSUE THREAD

**Issue by tomas-c** [spring-projects/spring-data-jpa#3025]
```
  @Query("SELECT ce.id FROM CalendarEvent ce WHERE (ce.endDate - ce.startDate) > 5 MINUTE")
  fun test(): List<UUID>
```

fails with

```
org.springframework.data.jpa.repository.query.BadJpqlGrammarException: Line 1:73 extraneous input 'MINUTE' expecting <EOF>; Bad JPQL grammar [SELECT ce.id FROM CalendarEvent ce WHERE (ce.endDate - ce.startDate) > 5 MINUTE]
  at app//org.springframework.data.jpa.repository.query.BadJpqlGrammarErrorListener.syntaxError(BadJpqlGrammarErrorListener.java:39)
  at app//org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
  at app//org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:543)
  at app//org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:377)
  at app//org.antlr.v4.runtime.DefaultErrorStrategy.singleTokenDeletion(DefaultErrorStrategy.java:548)
  at app//org.antlr.v4.runtime.DefaultErrorStrategy.recoverInline(DefaultErrorStrategy.java:467)
  at app//org.antlr.v4.runtime.Parser.match(Parser.java:207)
  at app//org.springframework.data.jpa.repository.query.HqlParser.start(HqlParser.java:252)
  at app//org.springframework.data.jpa.repository.query.HqlQueryParser.parseQuery(HqlQueryParser.java:53)
  at app//org.springframework.data.jpa.repository.query.HqlQueryParser.parse(HqlQueryParser.java:63)
  at app//org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.lambda$new$0(JpaQueryParserSupport.java:182)
  at app//org.springframework.data.util.Lazy.getNullable(Lazy.java:245)
  at app//org.springframework.data.util.Lazy.get(Lazy.java:114)
  at app//org.springframework.data.jpa.repository.query.JpaQueryParserSupport$ParseState.getContext(JpaQueryParserSupport.java:194)
  at app//org.springframework.data.jpa.repository.query.JpaQueryParserSupport.renderSortedQuery(JpaQueryParserSupport.java:54)
```

Used to work before updating to Spring Data JPA 3.1.0

**Comment by gregturn** [comment]
That's merged to `main` and backported to `3.1.x`
