### ISSUE TITLE
@EntityGraph's attributePaths not working with subclass property

### ISSUE THREAD

**Issue by Aikain** [spring-projects/spring-data-jpa#3034]
Since version 3.1.0, `@EntityGraph(type = EntityGraphType.FETCH, attributePaths = "childDependency"})` don't work.

```java
@Entity
public abstract class Parent extends AbstractPersistable<Long> {

    @ManyToOne(cascade = CascadeType.ALL)
    private Dependency dependency;

    // getters, setters, ...
}

@Entity
public class Child extends Parent {

    @ManyToOne(cascade = CascadeType.ALL)
    private Dependency childDependency;

    // getters, setters, ...
}


public interface ParentRepository extends JpaRepository<Parent, Long> {

    @EntityGraph(type = EntityGraphType.FETCH, attributePaths = {"dependency", "childDependency"})
    @Override
    List<Parent> findAll();
}

@Test
void test() {
    Child child = new Child();
    child.setDependency(new Dependency("test"));
    child.setChildDependency(new Dependency("test2"));
    parentRepository.save(child);

    List<Parent> parentList = parentRepository.findAll();

    assertThat(parentList).hasSize(1);
    assertEquals("test", parentList.get(0).getDependency().getTest());  // OK
    assertEquals("test2", ((Child)parentList.get(0)).getChildDependency().getTest()); // LazyInitializationException
}
```

**Comment by mp911de** [comment]
Have you checked whether specifying the fetch graph works when you apply using `EntityManager` directly?

**Comment by Aikain** [comment]
I have never used EntityManager directly. Did you mean something like this?

```java
@PersistenceContext
private EntityManager entityManager;

@Transactional
@Test
void test2() {
    Child child = new Child();
    child.setDependency(new Dependency("test"));
    child.setChildDependency(new Dependency("test2"));
    entityManager.persist(child);
    entityManager.flush();
    entityManager.clear();

    EntityGraph<Parent> entityGraph = entityManager.createEntityGraph(Parent.class);
    entityGraph.addAttributeNodes("dependency");
    entityGraph.addAttributeNodes("childDependency");

    Map<String, Object> properties = new HashMap<>();
    properties.put("jakarta.persistence.fetchgraph", entityGraph);

    Parent obj = entityManager.find(Parent.class, child.getId(), properties);
    assertTrue(Hibernate.isInitialized(obj.getDependency()));                   // OK
    assertTrue(Hibernate.isInitialized(((Child)obj).getChildDependency()));     // Fail
}
```

If I created EntityGraph from Child class, it's working:

```java
@Transactional
@Test
void test3() {
    Child child = new Child();
    child.setDependency(new Dependency("test"));
    child.setChildDependency(new Dependency("test2"));
    entityManager.persist(child);
    entityManager.flush();
    entityManager.clear();

    EntityGraph<Child> entityGraph = entityManager.createEntityGraph(Child.class);
    entityGraph.addAttributeNodes("dependency");
    entityGraph.addAttributeNodes("childDependency");

    Map<String, Object> properties = new HashMap<>();
    properties.put("jakarta.persistence.fetchgraph", entityGraph);

    Parent obj = entityManager.find(Parent.class, child.getId(), properties);
    assertTrue(Hibernate.isInitialized(obj.getDependency()));                   // OK
    assertTrue(Hibernate.isInitialized(((Child)obj).getChildDependency()));     // OK
}
```

But I can't do this when there is multiple different subclass?

**Comment by mp911de** [comment]
> I have never used EntityManager directly. Did you mean something like this?

Yes, exactly. 

As in your example above:

> ```java
>     Parent obj = entityManager.find(Parent.class, child.getId(), properties);
>     assertTrue(Hibernate.isInitialized(obj.getDependency()));                   // OK
>     assertTrue(Hibernate.isInitialized(((Child)obj).getChildDependency()));     // Fail
> ```


That is exactly what Spring Data does because the repository uses `Parent` as domain type. The repository has no detail about the child type.

However, Spring Data JPA supports named entity graphs, see https://www.baeldung.com/spring-data-jpa-named-entity-graphs for an example.

Alternatively, if you define your repository query method to return `List<Child>`, then the fetch graph will be created using `Child` instead of `Parent`.

Closing this ticket as these are the supported options.

**Comment by Aikain** [comment]
Apologies if this seems mostly like a question for help. However, I think there is still a issue in here.

In a real situation, I have several subclasses, so I have to use a superclass.

Named entity graphs make the situation even worse. Named entity graph in superclass cannot use the attributes of the subclass and named entity graph in subclass cannot use the superclass. Or have I misunderstood how they work?

Attributes of subclasses worked in 3.0.7, so my question is why don't they work anymore in 3.1.0?

There is now more realistic example in my repository (https://github.com/Aikain/EntityGraphTest). All tests passed with version 3.0.7 (spring-boot-*, spring.data-jpa), but not when upgrade to version 3.1.0.

--------

In addition, if it's really the case that attributePaths doesn't support subclass attributes, shouldn't they throw the same error as trying to use something that doesn't exist?

```java
@EntityGraph(type = EntityGraphType.FETCH, attributePaths = {"dependency", "childDependency", "notExists"})
```

```
org.springframework.dao.InvalidDataAccessApiUsageException: Unable to locate Attribute with the given name [notExists] on this ManagedType [com.example.entitygraphtest.Parent]
	at org.springframework.orm.jpa.EntityManagerFactoryUtils.convertJpaAccessExceptionIfPossible(EntityManagerFactoryUtils.java:371)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:234)
        ...
Caused by: java.lang.IllegalArgumentException: Unable to locate Attribute with the given name [notExists] on this ManagedType [com.example.entitygraphtest.Parent]
	at org.hibernate.metamodel.model.domain.AbstractManagedType.checkNotNull(AbstractManagedType.java:281)
	at org.hibernate.metamodel.model.domain.AbstractManagedType.getAttribute(AbstractManagedType.java:154)
        ...
```

**Comment by mp911de** [comment]
> Attributes of subclasses worked in 3.0.7, so my question is why don't they work anymore in 3.1.0?

In recent months, most issues reporting something have been working a few versions ago in the context of Hibernate functionality stemmed from Hibernate breaking something. Have you tried downgrading Hibernate to 6.1? The major difference between Spring Data JPA 3.0.x and 3.1.x is that we build against a newer Hibernate version.

**Comment by Aikain** [comment]
It worked with hibernate-core 6.1.7.Final but not 6.2.0.Final or newer. So problem seems to be with Hibernate (or it dependencies?) and not Spring Data JPA.

Thanks!

**Comment by StefanLobbenmeierObjego** [comment]
> Named entity graph in superclass cannot use the attributes of the subclass
I am struggling with that as well

Did you end up reporting this issue to hibernate / could you link those issues up?

**Comment by Aikain** [comment]
> > Named entity graph in superclass cannot use the attributes of the subclass
> > I am struggling with that as well
> 
> Did you end up reporting this issue to hibernate / could you link those issues up?

I do not remember. I couldn't find that I reported forward and the project still seems to have a version that worked as I needed.
