### ISSUE TITLE
`@Query(value="TRUNCATE TABLE ...", nativeQuery = true)` fails with `ClassCastException`

### ISSUE THREAD

**Issue by Hasoo** [spring-projects/spring-data-jpa#3038]
I'm upgrading spring boot 2.7.13 from 2.4.0.
When executing @Query(value="TRUNCATE TABLE ...", nativeQuery=true), occurred below error.

Can you add a truncate table query like #2593 ?

```
Caused by: java.lang.ClassCastException: Cannot cast net.sf.jsqlparser.statement.truncate.Truncate to net.sf.jsqlparser.statement.select.Select at java.base/java.lang.Class.cast(Class.java:3605) ~[na:na]
at org.springframework.data.jpa.repository.query.JSqlParserQueryEnhancer.parseSelectStatement(JSqlParserQueryEnhancer.java:480) ~[spring-data-jpa-2.7.13.jar:2.7.13]
at org.springframework.data.jpa.repository.query.JSqlParserQueryEnhancer.parseSelectStatement(JSqlParserQueryEnhancer.java:493) ~[spring-data-jpa-2.7.13.jar:2.7.13]
```

**Comment by mp911de** [comment]
That's fixed now and backported to 2.7.x.
