### ISSUE TITLE
CrudRepository deleteAll() failing for entity with composite primary key

### ISSUE THREAD

**Issue by philiplowney** [spring-projects/spring-data-jpa#3065]
We are unable to use the CrudRepository.deleteAll() method for an entity. We are using the following dependencies:
```
        <spring.version>6.0.10</spring.version>
        <spring-data-jpa.version>3.1.1</spring-data-jpa.version>
        <hibernate.version>6.2.6.Final</hibernate.version>
```

## Entity Model
Our Entity Model consists of the following:

      ┌───────────┐       ┌────┐
      │FormVersion│*─────1│Form│
      └───────────┘       └────┘
            1
            │
            │
            *
       ┌─────────┐
       │FormInput│
       └─────────┘

Note that `FormVersion` entities have a composite primary key consisting of the Form ID and a version number.

## Bug
When we create more than one `FormVersion` entity and try to delete them all by using the `CrudRepository.deleteAll()` 
method, we encounter the following error:
```agsl

org.springframework.transaction.TransactionSystemException: Could not commit JPA transaction

	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:570)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:660)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:410)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	... omitted for brevity ...
Caused by: jakarta.persistence.RollbackException: Error while committing the transaction
	... omitted for brevity ...
Caused by: java.lang.NullPointerException: Cannot invoke java.util.Comparator.compare(Object, Object) because the return value of org.hibernate.type.descriptor.java.JavaType.getComparator() is null
	at org.hibernate.metamodel.mapping.AttributeMapping.compare(AttributeMapping.java:91)
	at org.hibernate.metamodel.mapping.EmbeddableMappingType.compare(EmbeddableMappingType.java:267)
	at org.hibernate.metamodel.mapping.internal.EmbeddedForeignKeyDescriptor.compare(EmbeddedForeignKeyDescriptor.java:226)
	at org.hibernate.action.internal.CollectionAction.compareTo(CollectionAction.java:166)
	at org.hibernate.action.internal.CollectionAction.compareTo(CollectionAction.java:30)
	at org.hibernate.engine.spi.ExecutableList.add(ExecutableList.java:221)
	at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:386)
	... omitted for brevity ...
```

Note that when the entity model is modified to remove the `FormInput` entity, the bug does _not_ occur. It may be related in some way to the composite primary key on the `FormVersion` entity being used as a foreign key by the `FormInput` entity.

## Possibly Related Bug
We are aware of an existing bug relating to `deleteAll()`: https://github.com/spring-projects/spring-data-jpa/issues/1960. I believe this is likely separate to this issue however because the workaround suggested - add getters and setters to all fields - does not apply here as all fields on entities already have getters and setters.

## Entity Model
Our entities are as follows:

```java
@Entity
public class Form {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}

@Entity
public class FormInput {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    @JoinColumns(foreignKey = @ForeignKey(name = "FK_Input_FormVersion"), value = {@JoinColumn(name = "form_id", updatable = false), @JoinColumn(name = "versionNumber", updatable = false)})
    private FormVersion formVersion;

    public FormInput(FormVersion formVersion) {
        this.formVersion = formVersion;
    }

    public FormInput() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public FormVersion getFormVersion() {
        return formVersion;
    }

    public void setFormVersion(FormVersion formVersion) {
        this.formVersion = formVersion;
    }

}

@Entity
public class FormVersion {

    @OneToMany(cascade = CascadeType.ALL, orphanRemoval = true, mappedBy = "formVersion")
    private List<FormInput> inputs;

    @EmbeddedId
    protected FormVersionId id;

    public FormVersionId getId() {
        return id;
    }

    public void setId(FormVersionId id) {
        this.id = id;
    }

    public FormVersion() {
        id = new FormVersionId();
    }

    public FormVersion(Form form, int version) {
        this();
        this.id.setForm(form);
        this.id.setVersionNumber(version);
    }

    public List<FormInput> getInputs() {
        return inputs;
    }

    public void setInputs(List<FormInput> inputs) {
        this.inputs = inputs;
    }

}

@Embeddable
public class FormVersionId implements Serializable {

    @ManyToOne
    @JoinColumn(name = "form_id")
    private Form form;

    private Integer versionNumber;

    public Form getForm() {
        return form;
    }

    public void setForm(Form form) {
        this.form = form;
    }

    public Integer getVersionNumber() {
        return versionNumber;
    }

    public void setVersionNumber(Integer versionNumber) {
        this.versionNumber = versionNumber;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof FormVersionId)) {
            return false;
        }
        FormVersionId that = (FormVersionId) o;
        return form.getId().equals(that.form.getId()) && versionNumber.equals(that.versionNumber);
    }

    @Override
    public int hashCode() {
        return Objects.hash(form, versionNumber);
    }
}
```

## Test Case
We have created a project on Github reproducing the issue here: https://github.com/philiplowney/deleteall-bug-spring-data-jpa.

**Comment by mp911de** [comment]
I'm able to reproduce the bug when running find and delete within the same transaction.
The reduced reproducer is:

```java
new TransactionTemplate(tm).executeWithoutResult(status -> {
	formVersionRepository.findAll().forEach(it -> {
		entityManager.remove(it);
	});
});
```

Please file a ticket against Hibernate as we cannot fix a deeply nested NPE originating from within Hibernate code.

**Comment by philiplowney** [comment]
Thank you for investigating and following up on this so quickly @mp911de , I will raise a bug with Hibernate.

**Comment by 4braincells** [comment]
Hi, @philiplowney, can you link the hibernate issue here? thx
