### ISSUE TITLE
Component at index 0 has no alias, but alias is required

### ISSUE THREAD

**Issue by fnasibov** [spring-projects/spring-data-jpa#3090]
Hi.
### The main question is, is this a bug or am I doing something wrong?
Getting `java.lang.IllegalArgumentException: Component at index 0 has no alias, but alias is required` on startup spring boot 3.1.2  (data-jpa starte version 3.1.2 ) app.
Here is example of query that fails.
```
import com.example.exploringstarters.model.Contact;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;

import java.util.List;
import java.util.UUID;

@Repository
public interface ContactRepository extends JpaRepository<Contact, UUID> {

    @Query("select contact from (select numeredContact, row_number() over(partition by numeredContact.name, numeredContact.phone) as num from Contact numeredContact ) as contact where contact.num = 1")
    List<Contact> findAllWithUniqueNameAndPhonePair();
}
```
And [here](https://github.com/fnasibov/exploringStarters/tree/master) test app that you can run localy and get this error. 

BTW native query works!
```
@Repository
public interface ContactRepository extends JpaRepository<Contact, UUID> {

    @Query(value = "select *" +
            " from (select *, row_number() over (partition by name, phone) as n from contact as c) as cc" +
            " where cc.n = 1",
            nativeQuery = true)
    List<Contact> findAllWithUniqueNameAndPhonePair();
}
```
in debuger i see (in class  org.hibernate.query.derived.AnonymousTupleType)  that component have alias but getAlias() returns null;
![debugger screenshot](https://github.com/spring-projects/spring-data-jpa/assets/39213506/89b93aa8-f682-4d75-be00-70c0b7a1fced)

so full stacktrace
```
Caused by: java.lang.IllegalArgumentException: Component at index 0 has no alias, but alias is required
	at org.hibernate.query.derived.AnonymousTupleType.<init>(AnonymousTupleType.java:61) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.derived.AnonymousTupleType.<init>(AnonymousTupleType.java:50) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.sqm.tree.domain.SqmDerivedRoot.<init>(SqmDerivedRoot.java:35) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitRootSubquery(SemanticQueryBuilder.java:2029) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitRootSubquery(SemanticQueryBuilder.java:253) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.grammars.hql.HqlParser$RootSubqueryContext.accept(HqlParser.java:2451) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitEntityWithJoins(SemanticQueryBuilder.java:1874) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitFromClause(SemanticQueryBuilder.java:1865) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitQuery(SemanticQueryBuilder.java:1141) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitQuerySpecExpression(SemanticQueryBuilder.java:937) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitQuerySpecExpression(SemanticQueryBuilder.java:253) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.grammars.hql.HqlParser$QuerySpecExpressionContext.accept(HqlParser.java:1818) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSimpleQueryGroup(SemanticQueryBuilder.java:931) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSimpleQueryGroup(SemanticQueryBuilder.java:253) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.grammars.hql.HqlParser$SimpleQueryGroupContext.accept(HqlParser.java:1711) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitSelectStatement(SemanticQueryBuilder.java:418) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.visitStatement(SemanticQueryBuilder.java:377) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.SemanticQueryBuilder.buildSemanticModel(SemanticQueryBuilder.java:295) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
	at org.hibernate.query.hql.internal.StandardHqlTranslator.translate(StandardHqlTranslator.java:81) ~[hibernate-core-6.2.6.Final.jar:6.2.6.Final]
```

**Comment by gregturn** [comment]
I can the issue (once I added testcontainers to the reproducer), however, this stacktrace appears deeply buried inside Hibernate code.

Therefore, I believe this is a Hibernate issue. I'd suggest creating a reproducer based purely on Hibernate and submitting an issue with them.

To get more info, you can also add the following to your `application.properties` file:
```
logging.level.org.springframework.data.jpa=trace
logging.level.org.springframework.jdbc=debug
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.orm.jdbc.bind=trace
```

If you think this is actually a Spring Data issue, please provide a reproducer for the issue including a test case that demonstrates the correct behavior using the EntityManager directly.

**Comment by fnasibov** [comment]
Thank you. Submited the [issue ](https://hibernate.atlassian.net/browse/HHH-17018)to hibernate

**Comment by gregturn** [comment]
In light of the comments, I'm closing this ticket. Feel free to come back if the issue surfaces on our end.
