### ISSUE TITLE
graalvm Error 

### ISSUE THREAD

**Issue by FPEsocrter** [spring-projects/spring-data-jpa#3178]
10:28:24.285 ERROR [36morg.springframework.boot.SpringApplication.reportFailure:824[0;39m - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory': error processing @TypeBinderType annotation '@org.hibernate.annotations.Comment(on="", value="\u4e3b\u952e")'
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1155)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:932)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at cn.escort.LauncherMain.main(LauncherMain.java:14)
Caused by: org.hibernate.AnnotationException: error processing @TypeBinderType annotation '@org.hibernate.annotations.Comment(on="", value="\u4e3b\u952e")'
        at org.hibernate.boot.model.internal.EntityBinder.callTypeBinders(EntityBinder.java:283)
        at org.hibernate.boot.model.internal.EntityBinder.bindEntityClass(EntityBinder.java:245)
        at org.hibernate.boot.model.internal.AnnotationBinder.bindClass(AnnotationBinder.java:417)
        at org.hibernate.boot.model.source.internal.annotations.AnnotationMetadataSourceProcessorImpl.processEntityHierarchies(AnnotationMetadataSourceProcessorImpl.java:255)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess$1.processEntityHierarchies(MetadataBuildingProcess.java:275)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:318)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:1380)
        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1451)
        at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:75)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:376)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
        at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        ... 16 common frames omitted
Caused by: java.lang.InstantiationException: org.hibernate.binder.internal.CommentBinder
        at java.base@17.0.8/java.lang.Class.newInstance(DynamicHub.java:639)
        at org.hibernate.boot.model.internal.EntityBinder.callTypeBinders(EntityBinder.java:279)
        ... 30 common frames omitted
Caused by: java.lang.NoSuchMethodException: org.hibernate.binder.internal.CommentBinder.<init>()
        at java.base@17.0.8/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.8/java.lang.Class.newInstance(DynamicHub.java:626)
        ... 31 common frames omitted

**Comment by mp911de** [comment]
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/).

**Comment by FPEsocrter** [comment]
[
  {
    "name":"org.hibernate.binder.internal.CommentBinder",
    "methods":[{"name":"<init>","parameterTypes":[] }]
  }
]
