### ISSUE TITLE
JPA Projection failing if _ is the attribute Name. 

### ISSUE THREAD

**Issue by engineerscodes** [spring-projects/spring-data-jpa#3181]
```java
@Data
@AllArgsConstructor
@NoArgsConstructor
@Entity
public class Question {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID questionID;


    /**
     *  Many question mapped to one Project ID
     */
    @ManyToOne
    @JoinColumn(name = "fk_project_uuid",referencedColumnName = "id")
    private Project project;

    @Column(name = "question_img",nullable = false)
    @Lob
    private byte[] question;


    @JdbcTypeCode(SqlTypes.JSON)
    @Column(columnDefinition = "jsonb",nullable = false)
    private List<Options> options;


    @Column(name = "answer_index",nullable = false)
    private long answer_id;

}
```

Error : 
```java

Caused by: org.springframework.data.mapping.PropertyReferenceException: No property 'answer' found for type 'Question'
	at org.springframework.data.mapping.PropertyPath.<init>(PropertyPath.java:90) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:405) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.mapping.PropertyPath.create(PropertyPath.java:381) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.mapping.PropertyPath.lambda$from$0(PropertyPath.java:334) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at java.base/java.util.concurrent.ConcurrentMap.computeIfAbsent(ConcurrentMap.java:330) ~[na:na]
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:316) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.mapping.PropertyPath.from(PropertyPath.java:299) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:165) ~[spring-data-jpa-3.1.4.jar:3.1.4]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:141) ~[spring-data-jpa-3.1.4.jar:3.1.4]
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.complete(JpaQueryCreator.java:60) ~[spring-data-jpa-3.1.4.jar:3.1.4]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81) ~[spring-data-commons-3.1.4.jar:3.1.4]
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:218) ~[spring-data-jpa-3.1.4.jar:3.1.4]
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:103) ~[spring-data-jpa-3.1.4.jar:3.1.4]
	... 60 common frames omitted

```

MY DTO : 
```java
public record TEST(UUID questionID, byte[] question, List<Options> options,long answer_id) {
}
```

IT work If I remove _ from **answer_id** and make it **answerID** 
```java
   @Column(name = "answer_index",nullable = false)
    private long answerID;
```
and DTO to 
```java 
public record TEST(UUID questionID, byte[] question, List<Options> options,long answerID) {
}
```
![image](https://github.com/spring-projects/spring-data-jpa/assets/68312849/ad5984ed-9175-4c05-979c-738b32332360)

**Comment by engineerscodes** [comment]
**Here you can see the function PropertyPath is string name agrument has answer**

![image](https://github.com/spring-projects/spring-data-jpa/assets/68312849/2938cb2c-5645-4728-9f30-8f5100f64645)

**Comment by engineerscodes** [comment]
I think I found it but don't understand why 
![image](https://github.com/spring-projects/spring-data-jpa/assets/68312849/868a75d6-81fd-4d5f-9935-75fea955e4b4)
![image](https://github.com/spring-projects/spring-data-jpa/assets/68312849/aa52f756-ca5b-4073-8918-9586c31b2e76)

**Comment by engineerscodes** [comment]
Thank you @gregturn
