### ISSUE TITLE
Caused by: org.hibernate.query.SemanticException: Cannot compare left expression of type 'java.io.Serializable' with right expression of type 'java.lang.Long'

### ISSUE THREAD

**Issue by leshalv** [spring-projects/spring-data-jpa#3235]
```java
Caused by: org.hibernate.query.SemanticException: Cannot compare left expression of type 'java.io.Serializable' with right expression of type 'java.lang.Long'
	at org.hibernate.query.sqm.internal.TypecheckUtil.assertComparable(TypecheckUtil.java:338)
	at org.hibernate.query.sqm.tree.predicate.SqmComparisonPredicate.<init>(SqmComparisonPredicate.java:48)
	at org.hibernate.query.sqm.tree.predicate.SqmComparisonPredicate.<init>(SqmComparisonPredicate.java:34)
	at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.equal(SqmCriteriaNodeBuilder.java:2070)
	at org.hibernate.query.sqm.internal.SqmCriteriaNodeBuilder.equal(SqmCriteriaNodeBuilder.java:189)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator$PredicateBuilder.build(JpaQueryCreator.java:312)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.toPredicate(JpaQueryCreator.java:210)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.create(JpaQueryCreator.java:121)
	at org.springframework.data.jpa.repository.query.JpaQueryCreator.create(JpaQueryCreator.java:60)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createCriteria(AbstractQueryCreator.java:119)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:95)
	at org.springframework.data.repository.query.parser.AbstractQueryCreator.createQuery(AbstractQueryCreator.java:81)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$QueryPreparer.<init>(PartTreeJpaQuery.java:218)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery$CountQueryPreparer.<init>(PartTreeJpaQuery.java:361)
	at org.springframework.data.jpa.repository.query.PartTreeJpaQuery.<init>(PartTreeJpaQuery.java:102)
	... 54 common frames omitted
```

Use this example to reproduce:

[issues-3235.zip](https://github.com/spring-projects/spring-data-jpa/files/13422002/issues-3235.zip)

**Comment by mp911de** [comment]
This is a Hibernate issue caused by your configuration setup. Hibernate sees only the `Serializable` part on the query and fails instead of properly applying long comparison.

This issue can be easily reproduced with:

```
CriteriaBuilder cb = em.getCriteriaBuilder();
CriteriaQuery<UserEntity> query = cb.createQuery(UserEntity.class);
Root<UserEntity> from = query.from(UserEntity.class);
query.where(cb.equal(from.get("id"), cb.parameter(Long.class)));
```

Please file a bug report at Hibernate.

Note that passing on the actual value works:

```
CriteriaBuilder cb = em.getCriteriaBuilder();
CriteriaQuery<UserEntity> query = cb.createQuery(UserEntity.class);
Root<UserEntity> from = query.from(UserEntity.class);
query.where(cb.equal(from.get("id"), 1L));
```

**Comment by leshalv** [comment]
https://hibernate.atlassian.net/browse/HHH-17454

**Comment by drewhk** [comment]
We get this same issue for all repository interfaces where there are generics involved. E.g. 
```
findByIdAndActiveTrue(java.lang.Object); Cannot compare left expression of type 'java.lang.Long' with right expression of type 'java.lang.Object'
```
 where `Object` comes into play only because of type erasure. We are just using plain `CRUDPagingAndSortingRepository<T, ID>, JpaRepository<T, ID>` and the `@Query` annotation, no criteria API is used at all.
 
 I hope Hibernate fixes this soon.

**Comment by Herzenkin** [comment]
Hi @mp911de !

I'm in the middle of upgrading to SpringBoot 3.2.2 and I'm still suffering from the very similar issue (just quite simple HQL query with JOIN statement):

> org.hibernate.query.SemanticException: Cannot compare left expression of type 'java.lang.Long' with right expression of type com.custom.PartEntity

I see that I'm not alone with this problem - as there is an open ticket to Hibernate ORM (https://hibernate.atlassian.net/browse/HHH-17595). And seems like there is some integration issue with Spring Data as this issue cannot be reproduced just with bare Hibernate 6.4.1.

**Comment by amirensit** [comment]
I am facing the same error.
Any solution ?

**Comment by maitrisheth65** [comment]
I am trying to update spring from 2.7.3 to 3.2.3 and I am facing the same issue

**Comment by amirensit** [comment]
For my case I went to back to hibernate 6.2 versions.

**Comment by wagnercosta-elo** [comment]
Alguma novidade sobre ?

**Comment by rishiraj88** [comment]
> Alguma novidade sobre ?
Não, nenhum ainda. No news yet.
