### ISSUE TITLE
TransactionRequiredException

### ISSUE THREAD

**Issue by gusega** [spring-projects/spring-data-jpa#3237]
Hi all.

First of all, sorry for creating an issue, but I couldn't find any other answers to this problem, so here it goes.

My AspectJ interceptor around my method:
```java
@Around("@annotation(com.my.TransactionalAndDryRun)")
public Object rollBackOrCommit(ProceedingJoinPoint joinPoint) throws Throwable {
    MethodSignature signature = (MethodSignature) joinPoint.getSignature();
    Object[] args = joinPoint.getArgs();
    boolean isDryRun = isDryRun(signature, args);
    TransactionStatus transactionStatus = transactionTemplate.getTransactionManager().getTransaction(definition);
    Try<Object> outCome = transactionTemplate.execute(status -> {
            Try<Object> proceedOutcome = Try.of(joinPoint::proceed);
            if (dryRun || proceedOutcome.isFailure) {
                transactionTemplate.getTransactionManager().rollback(transactionStatus)
            } else {
                transactionTemplate.getTransactionManager().commit(transactionStatus);
            }
    })
}
```

The method: 
```java
@TransactionalAndDryRun
void myMethod(boolean dryRun) {
    // create an entity and save it to database via a method annotated with @jakarta.transaction.Transactional
    TransactionSynchronizationManager.registerSynchronization(new TransactionSynchronization() {
      public void afterCommit() {
         // send entity to kafka
         // update entity status via a method annotated with @jakarta.transaction.Transactional
      }
    })
}
```

When updating entity status, I get the following exception:

```
org.springframework.dao.InvalidDataAccessApiUsageException: Executing an update/delete query
...
Caused by: jakarta.persistence.TransactionRequiredException: Executing an update/delete query
at org.hibernate.internal.AbstractSharedSessionContract.checkTransactionNeededForUpdateOperation(AbstractSharedSessionContract.java:471)
at org.hibernate.query.sqm.internal.QuerySqmImpl.executeUpdate(QuerySqmImpl.java:701)
at org.springframework.data.jpa.repository.query.JpaQueryExecution$ModifyingExecution.doExecute(JpaQueryExecution.java:266)
at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:149)
at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:137)
at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:136)
at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:120)
at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:72)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:391)
at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
```

in my logs I see:
```
[https-jsse-nio-8443-exec-5] DEBUG o.s.orm.jpa.JpaTransactionManager - Found thread-bound EntityManager [SessionImpl(403000128PersistenceContext[...])] for JPA transaction
[https-jsse-nio-8443-exec-5] DEBUG o.s.orm.jpa.JpaTransactionManager - Participating in existing transaction
[https-jsse-nio-8443-exec-5] DEBUG o.s.orm.jpa.JpaTransactionManager - Participating transaction failed - marking existing transaction as rollback-only
[https-jsse-nio-8443-exec-5] DEBUG o.s.orm.jpa.JpaTransactionManager - Setting JPA transaction on EntityManager [SessionImpl(403000128PersistenceContext[...])] rollback-only
```

So it looks like 
Updating entity status runs inside the existing transaction, but for some reason when it's the time is to actually do the update the database, there is no transaction available.

I can only reproduce this issue in one of our integration tests on our CI environment. Locally I cannot reproduce it. When I run it locally, it creates a new transaction instead of participating in the existing one.
What can I do? Maybe add print some extra logs? What should I look at?

**Comment by mp911de** [comment]
First of all, let's try to understand what you're trying to achieve. Why are you running your own aspect on methods to wrap these with transactions although there's `@Transactional` in place?

Additionally, the code snippet does what `TransactionTemplate` already handles: Opening and cleaning up transactions. Spring's `TransactionAspectSupport` ships with support for `io.vavr.control.Try` so I'm having a hard time understanding the need for your own aspect.

**Comment by gusega** [comment]
@mp911de I updated my code snippet. The reason for custom aspect is that I have a `dryRun` parameter in my method. If user passes `dryRun` parameter, the transaction is not committed.

**Comment by mp911de** [comment]
I see. It would be still much easier to wrap your `TransactionManager` and call `rollback` in your own implementation than duplicating transaction control. You can always hold the flag to dry-run in a `ThreadLocal`.

**Comment by mp911de** [comment]
As there isn't much to do here and the issues stem from your own implementation, I'm going to close the issue here.

**Comment by gusega** [comment]
It seems that the issue is actions within `afterCommit()` must be transactional with `PROPAGATION_REQUIRES_NEW`.
By the way, the `commitTransactionAfterReturning()` in `org.springframework.transaction.interceptor.TransactionAspectSupport` has quite confusing name. It makes think that transaction commits later, meanwhile it is committed inside this method.   Maybe  calling it `transactionIsCommittedWhenReturned()` would make it more clear.
