### ISSUE TITLE
interface-based projection ignores unsigned Int

### ISSUE THREAD

**Issue by yasser-mas2** [spring-projects/spring-data-jpa#3238]
I have a custom query that uses interface-based projection, the table id is unsigned int and the interface like the below 

```
public interface ABCD {

    Long getId();
   .....
```

If I select any record that have id greater than `2147483647` the application throws the below exception 

```
com.mysql.cj.exceptions.NumberOutOfRange: Value '2157811816' is outside of valid range for type java.lang.Integer

```

This happens with interface-based projection only, I can select the table records and map it to the regular entity even without defining the column definition just defining the id as a Long

**Comment by mp911de** [comment]
`com.mysql.cj.exceptions.NumberOutOfRange` is a MySQL exception. Care to provide a reproducer?

**Comment by yasser-mas2** [comment]
yes, this is the full logs 

```
2023-11-23 21:17:25.574 ERROR 1 --- [p-nio-80-exec-4] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value '2157811816' is outside of valid range for type java.lang.Integer
2023-11-23 21:17:25.579 ERROR 1 --- [p-nio-80-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute query; SQL [ .... ]; nested exception is org.hibernate.exception.DataException: could not execute query] with root cause

com.mysql.cj.exceptions.NumberOutOfRange: Value '2157811816' is outside of valid range for type java.lang.Integer
	at com.mysql.cj.result.IntegerValueFactory.createFromLong(IntegerValueFactory.java:62) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.result.IntegerValueFactory.createFromLong(IntegerValueFactory.java:44) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeUInt4(MysqlTextValueDecoder.java:101) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:105) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1296) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:797) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:818) ~[mysql-connector-java-8.0.21.jar!/:8.0.21]
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java) ~[HikariCP-3.4.5.jar!/:na]
	at org.hibernate.type.descriptor.sql.IntegerTypeDescriptor$2.doExtract(IntegerTypeDescriptor.java:62) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.4.21.Final.jar!/:5.4.21.Final]
```


I'm using mysql v8, please check the steps to re-produce 

01- Create table with id int unsigned 

```
    CREATE TABLE `test` (
  `id` int unsigned NOT NULL,
  `name` varchar(50) NOT NULL ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB ;

INSERT INTO `test` (`id`, `name`) VALUES ('2157811816', 'test');
INSERT INTO `test` (`id`, `name`) VALUES ('2157811817', 'test2');

```

in application just create basic spring project and create this interface 

```
public interface testResult {

    Long getId();
    String getName();
}
```

in testRepo just add this query 

```
    @Query(value = "SELECT * from test where name = :name ", nativeQuery = true)
    testResult findByName(String name);
```
or also use this 

```
    @Query(value = "SELECT id from test where name = :name ", nativeQuery = true)
    Long findByName(String name);

    @Query(value = "SELECT id from test where name = :name ", nativeQuery = true)
    BigInteger findByName(String name);

```




all of the upper queries will not work, it will only work if the query returns an entity `Test`  ( that annotated with @entity )  like 

```

@Data
@Entity
@Table(name = "test")
public class Test {
    @Id
    private Long id;
    @Column(name = "name")
    private String name;
}
    @Query(value = "SELECT * from test where name = :name ", nativeQuery = true)
    Test findByName(String name);


```

**Comment by mp911de** [comment]
The stack trace is still truncated and it only shows Hibernate elements. As the errors happen within Hibernate and MySQL code, that isn't something that relates to Spring Data.

**Comment by yasser-mas2** [comment]
```
2023-11-27 21:13:29.192 ERROR 10836 --- [nio-8060-exec-2] o.h.engine.jdbc.spi.SqlExceptionHelper   : Value '2157811816' is outside of valid range for type java.lang.Integer
2023-11-27 21:13:29.204 ERROR 10836 --- [nio-8060-exec-2] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute query; SQL [ ]; nested exception is org.hibernate.exception.DataException: could not execute query] with root cause

com.mysql.cj.exceptions.NumberOutOfRange: Value '2157811816' is outside of valid range for type java.lang.Integer
	at com.mysql.cj.result.IntegerValueFactory.createFromLong(IntegerValueFactory.java:62) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.result.IntegerValueFactory.createFromLong(IntegerValueFactory.java:44) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.protocol.a.MysqlTextValueDecoder.decodeUInt4(MysqlTextValueDecoder.java:101) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.decodeAndCreateReturnValue(AbstractResultsetRow.java:105) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.protocol.result.AbstractResultsetRow.getValueFromBytes(AbstractResultsetRow.java:241) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.protocol.a.result.TextBufferRow.getValue(TextBufferRow.java:132) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getObject(ResultSetImpl.java:1296) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:797) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.mysql.cj.jdbc.result.ResultSetImpl.getInt(ResultSetImpl.java:818) ~[mysql-connector-java-8.0.21.jar:8.0.21]
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getInt(HikariProxyResultSet.java) ~[HikariCP-3.4.5.jar:na]
	at org.hibernate.type.descriptor.sql.IntegerTypeDescriptor$2.doExtract(IntegerTypeDescriptor.java:62) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.type.descriptor.sql.BasicExtractor.extract(BasicExtractor.java:47) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:257) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:253) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.type.AbstractStandardBasicType.nullSafeGet(AbstractStandardBasicType.java:249) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.custom.ScalarResultColumnProcessor.extract(ScalarResultColumnProcessor.java:54) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.custom.ResultRowProcessor.buildResultRow(ResultRowProcessor.java:83) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.custom.ResultRowProcessor.buildResultRow(ResultRowProcessor.java:60) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.custom.CustomLoader.getResultColumnOrRow(CustomLoader.java:412) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.getRowFromResultSet(Loader.java:775) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.getRowsFromResultSet(Loader.java:1044) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.processResultSet(Loader.java:995) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.doQuery(Loader.java:964) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:350) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2887) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.doList(Loader.java:2869) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2701) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.Loader.list(Loader.java:2696) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.loader.custom.CustomLoader.list(CustomLoader.java:338) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.internal.SessionImpl.listCustomQuery(SessionImpl.java:2142) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.internal.AbstractSharedSessionContract.list(AbstractSharedSessionContract.java:1163) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.query.internal.NativeQueryImpl.doList(NativeQueryImpl.java:173) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1533) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1581) ~[hibernate-core-5.4.21.Final.jar:5.4.21.Final]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:567) ~[na:na]
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:409) ~[spring-orm-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at com.sun.proxy.$Proxy343.getSingleResult(Unknown Source) ~[na:na]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196) ~[spring-data-jpa-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88) ~[spring-data-jpa-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154) ~[spring-data-jpa-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142) ~[spring-data-jpa-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195) ~[spring-data-commons-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152) ~[spring-data-commons-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130) ~[spring-data-commons-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80) ~[spring-data-commons-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367) ~[spring-tx-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118) ~[spring-tx-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139) ~[spring-tx-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149) ~[spring-data-jpa-2.3.4.RELEASE.jar:2.3.4.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at com.sun.proxy.$Proxy218.findByHash(Unknown Source) ~[na:na]

```
