### ISSUE TITLE
when use "->>" in @Query(nativeQuery = true) .net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "->>" "->>"

### ISSUE THREAD

**Issue by billschen** [spring-projects/spring-data-jpa#3246]
I have one query method to select json data from  [mysql json column](https://dev.mysql.com/doc/refman/8.0/en/json.html) like
```java
@Query( value = " SELECT jdoc->>\"$.auth_corp_info.corp_name\" FROM `permanent` WHERE id =:id", nativeQuery = true)
    List<String> getCorpNames( @Param("id") Long id);
```
but I  I upgrade my proejct from spring boot 3.1.5 to 3.2.
 ParseException happen
```java
Caused by: net.sf.jsqlparser.parser.ParseException: Encountered unexpected token: "->>" "->>"
    at line 1, column 13.

Was expecting one of:

    "&"
    "::"
    "<<"
    ">>"
    "CONNECT"
    "EMIT"
    "GROUP"
    "HAVING"
    "INTO"
    "START"
    "WINDOW"
    "["
    "^"
    "|"
    <EOF>
    <ST_SEMICOLON>

        at net.sf.jsqlparser.parser.CCJSqlParser.generateParseException(CCJSqlParser.java:38866) ~[jsqlparser-4.6.jar:na]
        at net.sf.jsqlparser.parser.CCJSqlParser.jj_consume_token(CCJSqlParser.java:38696) ~[jsqlparser-4.6.jar:na]
        at net.sf.jsqlparser.parser.CCJSqlParser.Statement(CCJSqlParser.java:306) ~[jsqlparser-4.6.jar:na]
        at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:253) ~[jsqlparser-4.6.jar:na]
        at net.sf.jsqlparser.parser.CCJSqlParserUtil$1.call(CCJSqlParserUtil.java:250) ~[jsqlparser-4.6.jar:na]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[na:na]
```

**Comment by quaff** [comment]
I think it's necessary to fallback if jsqlparser doesn't recognize particular sql grammar since it's not a omniscient parser.

https://github.com/spring-projects/spring-data-jpa/blob/bac05b7392210f4ff222b45e2dcc06a8c80d2106/spring-data-jpa/src/main/java/org/springframework/data/jpa/repository/query/QueryEnhancerFactory.java#L66-L73

```java
			if (jSqlParserPresent) {
				try {
					return new JSqlParserQueryEnhancer(query);
				} catch (IllegalArgumentException ex) {
					if (ex.getCause() instanceof JSQLParserException) {
						// fallback
						return new DefaultQueryEnhancer(query);
					}
					throw ex;
				}
			}
```

**Comment by christophstrobl** [comment]
It seems the parser is able to work with 
```sql
SELECT jdoc->>'$.auth_corp_info.corp_name' FROM permanent WHERE id =:id
```
instead of 
```sql
SELECT jdoc->>\"$.auth_corp_info.corp_name\" FROM `permanent` WHERE id =:id
```

**Comment by christophstrobl** [comment]
closing this one for now since parsing works fine using single quotes as required by `JsqlParser`.
