### ISSUE TITLE
NPE in CriteriaUpdate when field is null using InheritanceType.JOINED and InlineMutationStrategy

### ISSUE THREAD

**Issue by jv-ribeiros** [spring-projects/spring-data-jpa#3278]
I'm using ```@Inheritance(strategy = InheritanceType.JOINED)``` with the property ```spring.jpa.properties.hibernate.query.mutation_strategy=org.hibernate.query.sqm.mutation.internal.inline. InlineMutationStrategy``` and CriteriaUpdate to manage my changes in the Repository. However, when a field is determined to be null it cannot make the change, even though the column in the database accepts null values, generating an NPE in the package.

```[19/12/2023 13:45:53.308] [JCMOBILE-API] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/api] threw exception [Request processing failed: java.lang.NullPointerException: Cannot invoke "org.hibernate.query.sqm.SqmExpressible.getExpressibleJavaType()" because the return value of "org.hibernate.query.sqm.tree.expression.JpaCriteriaParameter.getNodeType()" is null] with root cause
java.lang.NullPointerException: Cannot invoke "org.hibernate.query.sqm.SqmExpressible.getExpressibleJavaType()" because the return value of "org.hibernate.query.sqm.tree.expression.JpaCriteriaParameter.getNodeType()" is null
	at org.hibernate.query.sqm.tree.expression.JpaCriteriaParameter.getParameterType(JpaCriteriaParameter.java:130)
	at org.hibernate.query.sqm.internal.SqmUtil.determineParameterType(SqmUtil.java:513)
	at org.hibernate.query.sqm.internal.SqmUtil.createJdbcParameterBindings(SqmUtil.java:278)
	at org.hibernate.query.sqm.mutation.internal.MatchingIdSelectionHelper.selectMatchingIds(MatchingIdSelectionHelper.java:284)
	at org.hibernate.query.sqm.mutation.internal.inline.InlineUpdateHandler.execute(InlineUpdateHandler.java:116)
	at org.hibernate.query.sqm.mutation.internal.inline.InlineMutationStrategy.executeUpdate(InlineMutationStrategy.java:54)
	at org.hibernate.query.sqm.internal.MultiTableUpdateQueryPlan.executeUpdate(MultiTableUpdateQueryPlan.java:36)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doExecuteUpdate(QuerySqmImpl.java:705)
	at org.hibernate.query.sqm.internal.QuerySqmImpl.executeUpdate(QuerySqmImpl.java:675)```

**Comment by quaff** [comment]
It's more like a hibernate issue, You should report to https://hibernate.atlassian.net/ with [test case](https://github.com/hibernate/hibernate-test-case-templates).
