### ISSUE TITLE
Ordering by collection attribute and using Pageable returns wrong number of elements

### ISSUE THREAD

**Issue by lorenzbaier** [spring-projects/spring-data-jpa#3297]
Consider the following
```java
@Entity
public class Book {
  private Long id;
  private List<Author> authors;
}

@Repository
public interface BookRepo extends JpaRepository<Book, Long> {}
```

if i now call `bookRepo.findAll(PageRequest.of(0, 50, Sort.by("authors")))` where the requested page has a size of 50 and use sort by "authors" and each Book has 5 authors
then i will not get 50 books but less because the select statement which is generated looks something like

```sql
select *
from book
left join author on ...
order by author.id
offset 0 rows
fetch first 50 rows only
```

which does not include 50 books but only like 47

can someone tell me if this is a known issue and wether it is related to spring data or hibernate itself.

**Comment by mp911de** [comment]
If you would like us to spend some time helping you to diagnose the problem, please spend some time describing it and, ideally, providing a [minimal yet complete sample](https://stackoverflow.com/help/mcve) that reproduces the problem.
You can share it with us by pushing it to a separate repository on GitHub or by zipping it up and attaching it to this issue.

We've seen similar reports in conjunction with entity/fetch graphs.

**Comment by lorenzbaier** [comment]
[Uploading demo-jpa-repo-wrong-count-with-sort-collection-and-pagesize.zip…]()

**Comment by lorenzbaier** [comment]
[demo-jpa-repo-wrong-count-with-sort-collection-and-pagesize.zip](https://github.com/spring-projects/spring-data-jpa/files/13818288/demo-jpa-repo-wrong-count-with-sort-collection-and-pagesize.zip)

**Comment by mp911de** [comment]
This is a difference in how Hibernate runs queries. While Hibernate 5.x runs these queries correctly, Hibernate 6.x does not. For the query, we create a criteria query with a left outer join.

I'm able to reproduce the issue using the JPA API:

```java
CriteriaBuilder cb = em.getCriteriaBuilder();

CriteriaQuery<Book> cq = cb.createQuery(Book.class);
Root<Book> root = cq.from(Book.class);
Join<Object, Object> join = root.join("authors", JoinType.LEFT);
cq.orderBy(cb.asc(join));
TypedQuery<Book> query = em.createQuery(cq).setFirstResult(0).setMaxResults(50);
```

Running `TypedQuery<Book> query` yields 47 objects.

The query we run equals to `FROM Book b ORDER by b.authors`. Running this query fails with `NotYetImplementedFor6Exception`.


```
org.hibernate.NotYetImplementedFor6Exception: org.hibernate.query.sqm.sql.internal.PluralValuedSimplePathInterpretation
	at org.hibernate.query.sqm.sql.internal.PluralValuedSimplePathInterpretation.accept(PluralValuedSimplePathInterpretation.java:73) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitSortSpecification(AbstractSqlAstTranslator.java:2279) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitSortSpecification(AbstractSqlAstTranslator.java:2260) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.renderOrderBy(AbstractSqlAstTranslator.java:1866) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitOrderBy(AbstractSqlAstTranslator.java:1850) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitQuerySpec(AbstractSqlAstTranslator.java:1599) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.tree.select.QuerySpec.accept(QuerySpec.java:129) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.visitSelectStatement(AbstractSqlAstTranslator.java:834) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.translateSelect(AbstractSqlAstTranslator.java:707) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.sql.ast.spi.AbstractSqlAstTranslator.translate(AbstractSqlAstTranslator.java:645) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.buildCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:377) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:270) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performList(ConcreteSqmSelectQueryPlan.java:246) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.doList(QuerySqmImpl.java:546) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.spi.AbstractSelectionQuery.list(AbstractSelectionQuery.java:363) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.sqm.internal.QuerySqmImpl.list(QuerySqmImpl.java:1032) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at org.hibernate.query.Query.getResultList(Query.java:94) ~[hibernate-core-6.1.5.Final.jar:6.1.5.Final]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler.invoke(SharedEntityManagerCreator.java:401) ~[spring-orm-6.0.2.jar:6.0.2]
	at jdk.proxy2/jdk.proxy2.$Proxy93.getResultList(Unknown Source) ~[na:na]
```

You might want to reach out to the Hibernate team.

**Comment by lorenzbaier** [comment]
why do i not get an exception although i use spring boot 3.2 even tough it uses hibernate 6.4?

can you point me to the location where the jpql with the `FROM Book b ORDER by b.authors` gets "translated" using the criteria builder?

**Comment by lorenzbaier** [comment]
but when you build the query like your example with criteria builder, hibernate can not know that it should not apply the skip and take to the whole query...

**Comment by mp911de** [comment]
> but when you build the query like your example with criteria builder, hibernate can not know that it should not apply the skip and take to the whole query...

This has worked in Hibernate 5.

**Comment by lorenzbaier** [comment]
i just checked with hibernate5 and it is even more wrong because it returns duplicates of the books 😂

but also 47 unique entities by id

the query for hibernate5 looks like:

```sql
select book0_.id as id1_1_, book0_.title as title2_1_
from book book0_
left outer join book_authors authors1_ on book0_.id=authors1_.book_id
left outer join author author2_ on authors1_.authors_id=author2_.id
order by author2_.id asc
limit 50
```

**Comment by lorenzbaier** [comment]
issue created in hibernate https://hibernate.atlassian.net/browse/HHH-17610

**Comment by mp911de** [comment]
Thanks for the cross-link. You might want to drop the Criteria Query into the HHH ticket as we've observed many tickets being rejected right away if there's a slight mention of Spring as Spring problem 🤷
