### ISSUE TITLE
JPQL parser doesn't accept double-quoted string literals

### ISSUE THREAD

**Issue by Y-AH** [spring-projects/spring-data-jpa#3308]
While parsing JPQL in `@Query` annotation, the parsing removes the `"` from the query itself resulting in an invalid query passed to hibernate.

Sample:
Inside SampleRepository
```java
    @Query("select new com.example.demo.SampleObject(se.id, se.sampleValue, \"\") from SampleEntity se")
    List<SampleObject> getAllSampleObjects();
```

SampleObject.java
```java
@Data
@AllArgsConstructor
public class SampleObject {

    private Long id;
    private String sampleValue;
    private String additionalValue;

}
```

SampleEntity.java
```java
@Entity
@Getter
@Setter
public class SampleEntity {

    @GeneratedValue
    @Id
    private Long id;

    private String sampleValue;

}
```

The above code result in (spring 3.2.1)
```
org.hibernate.query.SyntaxException: At 1:63 and token ')', no viable alternative at input 'select new com.example.demo.SampleObject(se.id, se.sampleValue,*) from SampleEntity se' [select new com.example.demo.SampleObject(se.id, se.sampleValue,) from SampleEntity se]
	at org.hibernate.query.hql.internal.StandardHqlTranslator$1.syntaxError(StandardHqlTranslator.java:108) ~[hibernate-core-6.4.1.Final.jar:6.4.1.Final]
```

In spring 3.1.7
```
org.hibernate.query.sqm.ParsingException: line 1:63 no viable alternative at input 'selectnewcom.example.demo.SampleObject(se.id,se.sampleValue,)'
	at org.hibernate.query.hql.internal.StandardHqlTranslator$1.syntaxError(StandardHqlTranslator.java:46) ~[hibernate-core-6.2.17.Final.jar:6.2.17.Final]
```

The issue first encountered when migrating from spring boot 3.0 to 3.1. Also I noticed in spring 3.0 the QueryEnhancer does not do anything if the query does not have sorting, is there a reason why the new one tries to parse even if there is no sorting?

**Comment by christophstrobl** [comment]
Thanks for reporting - we'll have a look.

**Comment by christophstrobl** [comment]
The parser only allows single quotes when parsing jpql. We're working on relaxing this restriction.
