### ISSUE TITLE
ERROR [procedure name] is not a procedure with Postgres 12 after upgrading from Spring Boot 3.0.3 to > 3.1.0

### ISSUE THREAD

**Issue by fvclaus** [spring-projects/spring-data-jpa#3393]
After upgrading from 3.0.3 to 3.2.3 I received the following error when calling a `@Procedure` on a `JpaRepository`. This worked fine in 3.0.3 and the DB didn't change.

Minimal project to reproduce the error: https://github.com/fvclaus/spring-data-postgres-stored-procedure-bug
In the `pom.xml` change the spring boot version from `3.2.3` to `3.0.3` or the other way round and run `mvn install`.

Here is the output when running with 3.0.3:
```
2024-03-13T15:18:33.906+01:00 DEBUG 657282 --- [           main] org.hibernate.SQL                        : {call some_procedure(?)}
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.051 s - in fvclaus.springdatapostgresstoredprocedurebug.SpringDataPostgresStoredProcedureBugApplicationTests
2024-03-13T15:18:33.954+01:00  INFO 657282 --- [ionShutdownHook] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2024-03-13T15:18:33.956+01:00  INFO 657282 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2024-03-13T15:18:33.959+01:00  INFO 657282 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
```

Here the output with 3.2.3:
```
2024-03-13T15:18:50.104+01:00 DEBUG 657922 --- [spring-data-postgres-stored-procedure-bug] [           main] org.hibernate.SQL                        : call some_procedure(?)
2024-03-13T15:18:50.116+01:00  WARN 657922 --- [spring-data-postgres-stored-procedure-bug] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 42809
2024-03-13T15:18:50.116+01:00 ERROR 657922 --- [spring-data-postgres-stored-procedure-bug] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: some_procedure(character varying) is not a procedure
  Hint: To call a function, use SELECT.
  Position: 6
2024-03-13T15:18:50.119+01:00 DEBUG 657922 --- [spring-data-postgres-stored-procedure-bug] [           main] org.hibernate.SQL                        : call some_procedure(?)
2024-03-13T15:18:50.119+01:00  WARN 657922 --- [spring-data-postgres-stored-procedure-bug] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: 25P02
2024-03-13T15:18:50.119+01:00 ERROR 657922 --- [spring-data-postgres-stored-procedure-bug] [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : ERROR: current transaction is aborted, commands ignored until end of transaction block
```

Here is  stacktrace:
```
[ERROR] fvclaus.springdatapostgresstoredprocedurebug.SpringDataPostgresStoredProcedureBugApplicationTests.callProcedure -- Time elapsed: 0.503 s <<< ERROR!
org.springframework.dao.InvalidDataAccessResourceUsageException: 
Error calling CallableStatement.getMoreResults [ERROR: some_procedure(character varying) is not a procedure
  Hint: To call a function, use SELECT.
  Position: 6] [HikariProxyCallableStatement@851514585 wrapping call some_procedure(('1'))]; SQL [HikariProxyCallableStatement@851514585 wrapping call some_procedure(('1'))]
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:277)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:241)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:550)
	at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61)
	at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:335)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:135)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:220)
	at jdk.proxy2/jdk.proxy2.$Proxy121.someProcedure(Unknown Source)
	at fvclaus.springdatapostgresstoredprocedurebug.SpringDataPostgresStoredProcedureBugApplicationTests.callProcedure(SpringDataPostgresStoredProcedureBugApplicationTests.java:37)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: org.hibernate.exception.SQLGrammarException: Error calling CallableStatement.getMoreResults [ERROR: some_procedure(character varying) is not a procedure
  Hint: To call a function, use SELECT.
  Position: 6] [HikariProxyCallableStatement@851514585 wrapping call some_procedure(('1'))]
	at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:91)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:58)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
	at org.hibernate.result.internal.OutputsImpl.convert(OutputsImpl.java:96)
	at org.hibernate.result.internal.OutputsImpl.executeStatement(OutputsImpl.java:73)
	at org.hibernate.procedure.internal.ProcedureOutputsImpl.<init>(ProcedureOutputsImpl.java:49)
	at org.hibernate.procedure.internal.ProcedureCallImpl.buildOutputs(ProcedureCallImpl.java:721)
	at org.hibernate.procedure.internal.ProcedureCallImpl.getOutputs(ProcedureCallImpl.java:605)
	at org.hibernate.procedure.internal.ProcedureCallImpl.outputs(ProcedureCallImpl.java:858)
	at org.hibernate.procedure.internal.ProcedureCallImpl.execute(ProcedureCallImpl.java:842)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution$ProcedureExecution.doExecute(JpaQueryExecution.java:345)
	at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:92)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:149)
	at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:137)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:170)
	at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:158)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:143)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137)
	... 13 more
Caused by: org.postgresql.util.PSQLException: ERROR: some_procedure(character varying) is not a procedure
  Hint: To call a function, use SELECT.
  Position: 6
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:368)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:498)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:415)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgCallableStatement.executeWithFlags(PgCallableStatement.java:84)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:177)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyCallableStatement.execute(HikariProxyCallableStatement.java)
	at org.hibernate.result.internal.OutputsImpl.executeStatement(OutputsImpl.java:69)
	... 34 more
```

My current workaround is to change `@Procedure("some_procedure")`  to `@Query(value= "SELECT some_procedure(:some_id)", nativeQuery=true)`

**Comment by fvclaus** [comment]
That's fine with. We don't have automated test for those calls, but it is not such a big deal to retest the whole application. Do you mind explaining why this is not going to be fixed? `@Procedure`  worked before and I couldn't find any release notes that this changed.

**Comment by mp911de** [comment]
The change has happened inside of Hibernate so that isn't something we can fix. We can only outline how you could work around that issue.

**Comment by fvclaus** [comment]
Thanks. I think I have figured it out. Since Postgres 11, real [stored procedures](https://www.postgresql.org/docs/current/xproc.html) are supported (not just functions). If I change my code from `FUNCTION` to `PROCEDURE`, the test succeeds with 3.2.3 (but not with 3.0.3). I also scrolled through the Hibernate release notes (between 6.1.7 and 6.2.2), but couldn't find anything.
