### ISSUE TITLE
NPE in HqlQueryTransformer.isSubquery for UPDATE HQL

### ISSUE THREAD

**Issue by dforrest-es** [spring-projects/spring-data-jpa#3649]
With 3.2.11, repository initialization fails with
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.ParserRuleContext.getParent()" because "ctx" is null
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.isSubquery(HqlQueryTransformer.java:105) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.isSubquery(HqlQueryTransformer.java:105) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.isSubquery(HqlQueryTransformer.java:105) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.isSubquery(HqlQueryTransformer.java:105) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.isSubquery(HqlQueryTransformer.java:105) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.isSubquery(HqlQueryTransformer.java:105) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryTransformer.visitVariable(HqlQueryTransformer.java:362) ~[spring-data-jpa-3.2.11.jar:3.2.11]
	at org.springframework.data.jpa.repository.query.HqlQueryRenderer.visitVariable(HqlQueryRenderer.java:1) ~[spring-data-jpa-3.2.11.jar:3.2.11]
```

Issue is very similar to #2977 but for update clauses:

```
update MyEntityStaging AS mes
set mes.col = 'test'
where mes.id = 1
```

Entity:
```
@Entity
@NamedQuery(name = "MyEntity.updateCol", query = """
        update MyEntity AS mes
        set mes.col = 'test'
        where mes.id = 1
""")
class MyEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    private Long id;

    private String col;
}
```

Repository:
```
interface MyEntityRepository extends JpaRepository<MyEntity, Long> {
    @Modifying
    @Transactional
    void updateCol();
}
```

Reproducer:
[demo.zip](https://github.com/user-attachments/files/17514036/demo.zip)
Extract and run ./mvnw spring-boot:run to observe the exception.
In the pom.xml, change the spring-data-jpa.version from 3.2.11 to 3.2.10 and run again, now it works.

---

My investigation:

Specifically, [this change](https://github.com/spring-projects/spring-data-jpa/commit/b05ab571971ca79c4549cdb20e2fb0dc33bb3d06#diff-55e78c4ae5e50a5d678ac9efb0a94d6472a59dc5902b2d4e9ac06c64cc06c0c9R362) causes `HqlQueryTransformer#isSubquery(ParserRuleContext)` to be run for update clauses & likely needs the same fix from #2977 applied for `HqlParser.UpdateStatementContext` (see [commit 6b9d3e2](https://github.com/spring-projects/spring-data-jpa/commit/df7197a3f77aa46718d00bdb81cbecd55#diff-55e78c4ae5e50a5d678ac9efb0a94d6472a59dc5902b2d4e9ac06c64cc06c0c9R99-R100))

Wrokaround:
Removing the `AS` from the table alias bypass this error.

**Comment by christophstrobl** [comment]
Thank you @dforrest-es for reporting and analysis.

**Comment by klauss42** [comment]
The issue is also reproducible when switching from Spring Boot 3.3.4 to 3.3.5. If using the following pom in the example project from above:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.5</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>demo</description>
    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

When switching back to 3.3.4 the app starts up properly.

In my application I encountered the same issue with a @Query annotation:
```
@Transactional
  @Modifying
  @Query(
    """
      delete from ActivityDetailProjection a
        where a.activityDetailId.customerId= :customerId and a.activityDetailId.vendorId = :vendorId
    """
  )
  fun deleteByVendorId(
    customerId: String,
    vendorId: String,
  )
```

**Comment by ThomHurks** [comment]
Many of our services also had failed builds when updating to Spring Boot 3.3.5 due to this bug. The workaround is to put this in your POM 's properties:
```xml
<spring-data-bom.version>2024.0.4</spring-data-bom.version>
```
this will use the previous version of spring-data-jpa that works.

**Comment by dforrest-es** [comment]
Thanks for a quick fix @mp911de & @christophstrobl!

**Comment by Fabio1988** [comment]
Is there any ETA of releasing that fix?

**Comment by mp911de** [comment]
We do, check out the [Release Calender](https://spring.io/projects#release-calendar) for most recent schedule updates in accordance with the assigned milestone.
