### ISSUE TITLE
Upgrade to Eclipselink 5.0.0-B05

### ISSUE THREAD

**Issue by mp911de** [spring-projects/spring-data-jpa#3672]

**Comment by mp911de** [comment]
Failing tests:

```
Syntax error parsing [select concat(?1,u.id,?2) as id from User u]. 
[31, 33] The identification variable 'id' cannot be a reserved word. (select concat(?1, u.id, ?2) as  [ id ] ...
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.createQuery(EntityManagerImpl.java:1848)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.orm.jpa.ExtendedEntityManagerCreator$ExtendedEntityManagerInvocationHandler.invoke(ExtendedEntityManagerCreator.java:364)
	at jdk.proxy2/jdk.proxy2.$Proxy202.createQuery(Unknown Source)
	at org.springframework.data.jpa.repository.query.SimpleJpaQuery.validateQuery(SimpleJpaQuery.java:91)
	... 53 more
```
