### ISSUE TITLE
Improve the error message for when DataSource is not set. [DATAJPA-535]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-jpa#928]
**[Adam Berlin](https://jira.spring.io/secure/ViewProfile.jspa?name=aberlin@pivotallabs.com)** opened **[DATAJPA-535](https://jira.spring.io/browse/DATAJPA-535?redirect=false)** and commented

I ran across this yesterday when attempting to configure Spring Data JPA.  There are a couple of scenarios when the error messaging is confusing.

```
@Bean(name="entityManagerFactory")
public LocalContainerEntityManagerFactoryBean getEntityManagerFactory() {
    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setPackagesToScan("things");
    //factory.setDataSource(getDataSource());
    factory.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
    return factory;
}
```

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class things.OtherConfig: Invocation of init method failed; nested exception is org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1553) ~[spring-beans-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539) ~[spring-beans-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:475) ~[spring-beans-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:304) ~[spring-beans-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-4.0.4.RELEASE.jar:4.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:300) ~[spring-beans-4.0.4.RELEASE.jar:4.0.4.RELEASE]
Caused by: org.hibernate.HibernateException: Access to DialectResolutionInfo cannot be null when 'hibernate.dialect' not set
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.determineDialect(DialectFactoryImpl.java:104) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
	at org.hibernate.engine.jdbc.dialect.internal.DialectFactoryImpl.buildDialect(DialectFactoryImpl.java:71) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:209) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:111) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:234) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:206) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
```

Ideally it would tell me that I'm missing a Data Source, and where I should go to find out more about how to do so.

---
No further details from [DATAJPA-535](https://jira.spring.io/browse/DATAJPA-535?redirect=false)

**Comment by gregturn** [comment]
`LocalContainerEntityManagerFactoryBean` is a Spring Framework class, so I'm pinging them to see if they'd be willing to take possession of this issue.

**Comment by gregturn** [comment]
Given that the root exception is Hibernate specific, there is little to do on our end (Spring Data or Spring Framework).
